import React,{useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
import MemberPage from "./MemberPage";
import ChefPage from "./ChefPage";

const TITLE_MAX=120,MESSAGE_MAX=2000;
type Profile={id:string;full_name:string|null;email:string|null;role:string};
type Meal={id:string;meal_date:string;meal_type:string;name:string;description:string;allergens:string[]};
type Props={user:any;profile:any};
export default function AdminPage({user,profile}:Props){
 const [members,setMembers]=useState<Profile[]>([]),[meals,setMeals]=useState<Meal[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState(""),[tab,setTab]=useState("members");
 const [title,setTitle]=useState(""),[message,setMessage]=useState(""),[notice,setNotice]=useState(""),[preview,setPreview]=useState<"member"|"chef"|null>(null),[sending,setSending]=useState(false),[roleNotice,setRoleNotice]=useState("");
 async function load(){setLoading(true);setError("");const [p,m]=await Promise.all([supabase.from("profiles").select("id,full_name,email,role").order("full_name",{nullsFirst:false}),supabase.from("meals").select("id,meal_date,meal_type,name,description,allergens").order("meal_date").limit(100)]);if(p.error)setError(p.error.message);else setMembers(p.data||[]);if(m.error)setError(m.error.message);else setMeals(m.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function changeRole(id:string,role:string){if(saving)return;const target=members.find(m=>m.id===id);if(id===user?.id&&role!=="admin"&&!window.confirm(`Change your own role to ${role}? You will lose access to this Admin dashboard.`))return;setSaving(id);setError("");setRoleNotice("");const {error:e}=await supabase.from("profiles").update({role}).eq("id",id);if(e)setError(e.message);else{setMembers(x=>x.map(m=>m.id===id?{...m,role}:m));setRoleNotice(`${target?.full_name||target?.email||"Member"} is now ${role}.`)}setSaving(null)}
 async function sendAnnouncement(){if(sending)return;setNotice("");const t=title.trim(),msg=message.trim();if(!t||!msg){setNotice("Title and message are required.");return}if(t.length>TITLE_MAX||msg.length>MESSAGE_MAX){setNotice(`Keep the title under ${TITLE_MAX} characters and the message under ${MESSAGE_MAX}.`);return}setSending(true);const {data,error:e}=await supabase.rpc("send_member_announcement",{p_title:t,p_message:msg,p_type:"announcement"});setSending(false);if(e){setNotice(e.message);return}setNotice(`${data||0} members notified.`);setTitle("");setMessage("")}
 if(preview){return <div className="adminPreview"><div className="previewBar"><strong>Preview Mode</strong><span>Viewing the {preview} experience without changing your Admin role.</span><button onClick={()=>setPreview(null)}>← Back to Admin</button></div>{preview==="member"?<MemberPage user={user} profile={profile} hideMealRatings/>:<ChefPage user={user} profile={profile}/>}</div>}
 return <section className="roleWorkspace adminWorkspace"><div className="roleHero"><span>ADMIN</span><h1>Admin Dashboard</h1><p>Manage members, roles, menus and HouseEats settings.</p><div className="adminPreviewButtons"><button onClick={()=>setPreview("member")}>👤 Preview Member</button><button onClick={()=>setPreview("chef")}>🧑‍🍳 Preview Chef</button></div></div>{error&&<div className="error errorBanner"role="alert"><span><b>Admin action failed</b> {error}</span><button type="button"aria-label="Dismiss message"onClick={()=>setError("")}>✕</button></div>}<nav className="workspaceNav">{[["members","👥 Members"],["roles","🔐 Roles"],["chef","🧑‍🍳 Chef Management"],["menu","🍽️ Menu Oversight"],["notify","🔔 Notifications"],["settings","⚙️ Settings"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav>{loading?<div className="message">Loading admin data…</div>:<>
 {tab==="members"&&<div className="adminPanel panel"><div className="heading"><div><h2>Members</h2><p>{members.length} profiles</p></div><button onClick={load}>Refresh</button></div><div className="memberTable">{members.map(m=><div className="memberRow" key={m.id}><div><b>{m.full_name||"Unnamed member"}</b><small>{m.email||"No email shown"}</small></div><span>{m.role}</span></div>)}</div></div>}
 {tab==="roles"&&<div className="adminPanel panel"><h2>Roles</h2><p>Role changes are protected by Supabase permissions.</p>{roleNotice&&<div className="message"role="status">{roleNotice}</div>}<div className="memberTable">{members.map(m=><div className="memberRow" key={m.id}><div><b>{m.full_name||"Unnamed member"}</b><small>{m.email||"No email shown"}</small></div><select value={m.role} disabled={saving===m.id} onChange={e=>changeRole(m.id,e.target.value)}><option value="member">Member</option><option value="chef">Chef</option><option value="moderator">Moderator</option><option value="admin">Admin</option></select></div>)}</div></div>}
 {tab==="chef"&&<div className="panel"><h2>Chef Management</h2><div className="roleCards">{members.filter(m=>["chef","moderator"].includes(m.role)).map(m=><div className="roleCard" key={m.id}><b>{m.full_name||"Unnamed"}</b><span>{m.role}</span><small>{m.email||"No email"}</small></div>)}</div></div>}
 {tab==="menu"&&<div className="panel"><h2>Menu Oversight</h2>{meals.length?meals.map(m=><div className="roleCard" key={m.id}><b>{m.meal_date} · {m.meal_type}</b><span>{m.name}</span>{m.allergens?.length>0&&<small>⚠️ {m.allergens.join(", ")}</small>}</div>):<div className="message">No meals found.</div>}</div>}
 {tab==="notify"&&<div className="panel"><h2>Notifications</h2><p>Send an announcement to all Members.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Announcement title" maxLength={TITLE_MAX}/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message for Members" rows={5} maxLength={MESSAGE_MAX}/><button onClick={sendAnnouncement}disabled={sending}>{sending?"Sending…":"Send notification"}</button>{notice&&<div className="message">{notice}</div>}</div>}
 {tab==="settings"&&<div className="panel"><h2>Settings</h2><div className="message">HouseEats configuration is protected. Additional settings can be added here without weakening role controls.</div></div>}
 </>}</section>}
