import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

const allergens=["Milk","Eggs","Wheat","Soy","Peanuts","Tree Nuts","Fish","Shellfish","Sesame"];
const iso=(d:Date)=>d.toISOString().slice(0,10);
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const calendarStart=(d:Date)=>{const x=monthStart(d);x.setDate(x.getDate()-x.getDay());return x};
const calendarEnd=(d:Date)=>{const x=new Date(d.getFullYear(),d.getMonth()+1,0);x.setDate(x.getDate()+(6-x.getDay()));return x};

type Props={user:any;profile:any};
type Meal={id:string;meal_date:string;meal_type:string;name:string;description:string;allergens:string[]};

export default function ChefPage({user,profile}:Props){
 const [meals,setMeals]=useState<Meal[]>([]),[rsvps,setRsvps]=useState<any[]>([]),[allergyRows,setAllergyRows]=useState<any[]>([]),[late,setLate]=useState<any[]>([]),[tab,setTab]=useState("dashboard"),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState("");
 const [announcementTitle,setAnnouncementTitle]=useState(""),[announcementMessage,setAnnouncementMessage]=useState(""),[announcementStatus,setAnnouncementStatus]=useState("");
 const [month,setMonth]=useState(()=>monthStart(new Date()));
 const rangeStart=useMemo(()=>calendarStart(month),[month]);const rangeEnd=useMemo(()=>calendarEnd(month),[month]);
 async function load(){const {data:menu}=await supabase.from("menus").select("id").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(menu){const {data,e}=await supabase.from("meals").select("id,meal_date,meal_type,name,description,allergens").eq("menu_id",menu.id).gte("meal_date",iso(rangeStart)).lte("meal_date",iso(rangeEnd)).order("meal_date").order("meal_type");if(e)setError(e.message);setMeals(data||[])}else setMeals([]);const [r,a,l]=await Promise.all([supabase.from("rsvps").select("meal_id,user_id,attending"),supabase.from("member_allergies").select("user_id,allergen"),supabase.from("late_plates").select("id,meal_id,user_id,status,created_at").neq("status","cancelled")]);setRsvps(r.data||[]);setAllergyRows(a.data||[]);setLate(l.data||[])}
 useEffect(()=>{load()},[rangeStart.toISOString(),rangeEnd.toISOString()]);
 const conflicts=useMemo(()=>meals.map(m=>{const attending=new Set(rsvps.filter(r=>r.meal_id===m.id&&r.attending).map(r=>r.user_id));const matches=allergyRows.filter(a=>attending.has(a.user_id)&&m.allergens?.includes(a.allergen));return {...m,count:new Set(matches.map(x=>x.user_id)).size,allergens:[...new Set(matches.map(x=>x.allergen))]}}).filter(m=>m.count>0),[meals,rsvps,allergyRows]);
 const count=(id:string)=>rsvps.filter(r=>r.meal_id===id&&r.attending).length;
 async function updateMeal(id:string,field:string,value:any){setSaving(id);const {error:e}=await supabase.from("meals").update({[field]:value,updated_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else setMeals(x=>x.map(m=>m.id===id?{...m,[field]:value}:m));setSaving(null)}
 async function updateLate(id:string,status:string){const {error:e}=await supabase.from("late_plates").update({status}).eq("id",id);if(e)setError(e.message);else setLate(x=>x.map(l=>l.id===id?{...l,status}:l))}
 async function sendAnnouncement(){setAnnouncementStatus("");const title=announcementTitle.trim(),message=announcementMessage.trim();if(!title||!message){setAnnouncementStatus("Title and message are required.");return}const {data,error:e}=await supabase.rpc("send_member_announcement",{p_title:title,p_message:message,p_type:"announcement"});if(e){setAnnouncementStatus(e.message);return}setAnnouncementStatus(`${data||0} members notified.`);setAnnouncementTitle("");setAnnouncementMessage("")}
 async function signOut(){await supabase.auth.signOut()}
 const days=useMemo(()=>{const out=[];for(let d=new Date(rangeStart);d<=rangeEnd;d.setDate(d.getDate()+1))out.push(new Date(d));return out},[rangeStart,rangeEnd]);
 const mealFor=(d:Date)=>meals.filter(m=>m.meal_date===iso(d));
 const renderCalendarMeal=(m:Meal)=><article className="calendarMeal" key={m.id}><small>{m.meal_type} · {count(m.id)} attending</small><h3>{m.name}</h3>{m.allergens?.length>0&&<small>⚠️ {m.allergens.join(", ")}</small>}<div className="calendarActions"><button onClick={()=>{setTab("menu");setTimeout(()=>document.getElementById(`edit-${m.id}`)?.scrollIntoView({behavior:"smooth",block:"center"}),0)}}>Edit</button></div></article>;
 return <section className="roleWorkspace chefWorkspace"><header className="roleHero"><span>{profile?.role?.toUpperCase()}</span><h1>Chef Dashboard</h1><p>One shared monthly menu — the same calendar Members see.</p><button onClick={signOut}>Sign out</button></header>
 <nav className="workspaceNav">{[["dashboard","🧑‍🍳 Dashboard"],["menu","📅 Monthly Menu"],["alerts","⚠️ Allergy Alerts"],["headcount","👥 Headcounts"],["late","🥡 Late Plates"],["announce","🔔 Notify Members"],["print","🖨️ Print"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}{k==="alerts"&&conflicts.length?` (${conflicts.length})`:""}</button>)}</nav>{error&&<div className="error">{error}</div>}
 {tab==="dashboard"&&<section className="panel"><h2>Kitchen Overview</h2><div className="stats"><div><b>{meals.length}</b><span>Meals this month</span></div><div><b>{rsvps.filter(r=>r.attending).length}</b><span>RSVPs</span></div><div><b>{conflicts.length}</b><span>Allergy conflicts</span></div><div><b>{late.filter(l=>l.status==="requested").length}</b><span>Late plates</span></div></div></section>}
 {tab==="menu"&&<><section className="panel monthCalendar chefMonthCalendar"><div className="heading"><div><h2>{month.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><p>Shared monthly menu — matches the Member calendar.</p></div><div className="calendarActions"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><button onClick={()=>setMonth(monthStart(new Date()))}>Today</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></div><div className="calendarGrid monthGrid"><div className="calendarHeader">Sun</div><div className="calendarHeader">Mon</div><div className="calendarHeader">Tue</div><div className="calendarHeader">Wed</div><div className="calendarHeader">Thu</div><div className="calendarHeader">Fri</div><div className="calendarHeader">Sat</div>{days.map(d=>{const ds=iso(d),outside=d.getMonth()!==month.getMonth(),isToday=ds===iso(new Date());return <div className={`calendarCell ${outside?"outsideMonth":""} ${isToday?"today":""}`} key={ds}><div className="calendarDate">{d.getDate()}</div>{mealFor(d).map(renderCalendarMeal)}</div>})}</div></section><section className="panel"><h2>Edit Meals</h2>{meals.map(m=><article className="mealCard" id={`edit-${m.id}`} key={m.id}><div><small>{m.meal_date} · {m.meal_type}</small><input value={m.name} onChange={e=>updateMeal(m.id,"name",e.target.value)} /><textarea value={m.description||""} onChange={e=>updateMeal(m.id,"description",e.target.value)}/><div className="allergyGrid">{allergens.map(a=><label key={a}><input type="checkbox" checked={m.allergens?.includes(a)} onChange={()=>updateMeal(m.id,"allergens",m.allergens?.includes(a)?m.allergens.filter(x=>x!==a):[...(m.allergens||[]),a])}/>{a}</label>)}</div></div>{saving===m.id&&<small>Saving…</small>}</article>)}</section></>}
 {tab==="alerts"&&<section className="panel"><h2>Allergy Alerts</h2>{conflicts.length?conflicts.map(c=><article className="error" key={c.id}><b>{c.meal_date} · {c.meal_type} — {c.name}</b><span>{c.count} attending member(s) match: {c.allergens.join(", ")}</span></article>):<div className="message">No current RSVP allergy conflicts.</div>}</section>}
 {tab==="headcount"&&<section className="panel headcountPanel"><div className="heading"><div><h2>Headcounts</h2><p>Confirmed diners by meal. Only meals with activity are shown.</p></div><strong className="headcountTotal">{rsvps.filter(r=>r.attending).length} total RSVPs</strong></div><div className="headcountList">{meals.filter(m=>count(m.id)>0).map(m=><article className="headcountRow" key={m.id}><div className="headcountDate"><b>{new Date(`${m.meal_date}T12:00:00`).toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}</b><small>{m.meal_type}</small></div><div className="headcountMeal"><b>{m.name}</b>{m.allergens?.length>0&&<small>⚠️ {m.allergens.join(", ")}</small>}</div><div className="headcountNumber"><b>{count(m.id)}</b><span>attending</span></div></article>)}{meals.every(m=>count(m.id)===0)&&<div className="message">No confirmed RSVPs yet.</div>}</div></section>}
 {tab==="late"&&<section className="panel"><h2>Late Plates</h2>{late.length?late.map(l=><div className="roleCard" key={l.id}><b>{meals.find(m=>m.id===l.meal_id)?.name||"Meal"}</b><span>{l.status}</span>{l.status==="requested"&&<div><button onClick={()=>updateLate(l.id,"approved")}>Approve</button><button onClick={()=>updateLate(l.id,"ready")}>Ready</button></div>}</div>):<div className="message">No active late-plate requests.</div>}</section>}
 {tab==="announce"&&<section className="panel"><h2>Notify Members</h2><p>Send an announcement to all Members.</p><input value={announcementTitle} onChange={e=>setAnnouncementTitle(e.target.value)} placeholder="Announcement title" /><textarea value={announcementMessage} onChange={e=>setAnnouncementMessage(e.target.value)} placeholder="Message for Members" rows={5}/><button onClick={sendAnnouncement}>Send notification</button>{announcementStatus&&<div className="message">{announcementStatus}</div>}</section>}
 {tab==="print"&&<section className="panel printSheet"><h2>Kitchen Sheet</h2><p>{new Date().toLocaleDateString()}</p>{meals.filter(m=>m.meal_date===iso(new Date())).map(m=><article key={m.id}><h3>{m.meal_type}: {m.name}</h3><p>{count(m.id)} attending · {late.filter(l=>l.meal_id===m.id).length} late plates</p>{m.allergens?.length>0&&<p>Allergens: {m.allergens.join(", ")}</p>}</article>)}<button onClick={()=>window.print()}>Print Kitchen Sheet</button></section>}
 </section>}
