import React,{useEffect,useMemo,useState}from"react";
import{supabase}from"../lib/supabase";
import{eachDay,formatMealDate,formatMonthLabel,monthBounds,monthGridRange,parseMealDate,startOfToday,todayISODate,toISODate}from"../lib/calendar";
import{ALLERGENS,MEAL_REVIEW_COLUMNS,firstErrorMessage,fetchActiveMenuMeals,mealsOnDate,sortMeals,type Meal}from"../lib/meals";
import MealRatingSummary from"../components/MealRatingSummary";
import MonthlyPrintCalendar from"../components/MonthlyPrintCalendar";
import AnnouncementForm from"../components/AnnouncementForm";
type Props={user:any;profile:any};
export default function ChefPage({user,profile}:Props){
 const[meals,setMeals]=useState<Meal[]>([]),[rsvps,setRsvps]=useState<any[]>([]),[allergyRows,setAllergyRows]=useState<any[]>([]),[late,setLate]=useState<any[]>([]),[reviewRows,setReviewRows]=useState<any[]>([]),[tab,setTab]=useState("dashboard"),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState("");
 const[month,setMonth]=useState(()=>monthBounds(new Date()).start),[editing,setEditing]=useState<string|null>(null),[drafts,setDrafts]=useState<Record<string,Meal>>({});
 const range=useMemo(()=>monthGridRange(month),[month]);
 async function load(){
  setError("");
  const menu=await fetchActiveMenuMeals(range.start,range.end);
  if(menu.error)setError(menu.error.message);
  const loadedMeals=menu.meals;
  setMeals(loadedMeals);
  const todayStart=startOfToday();const tomorrow=new Date(todayStart);tomorrow.setDate(tomorrow.getDate()+1);
  const[r,a,l,rv]=await Promise.all([supabase.from("rsvps").select("meal_id,user_id,attending"),supabase.from("member_allergies").select("user_id,allergen"),supabase.from("late_plates").select("id,meal_id,user_id,status,created_at").neq("status","cancelled").gte("created_at",todayStart.toISOString()).lt("created_at",tomorrow.toISOString()),supabase.from("meal_reviews").select(MEAL_REVIEW_COLUMNS).in("meal_id",loadedMeals.map(m=>m.id)).order("created_at",{ascending:false})]);
  const rowError=firstErrorMessage(r.error,a.error,l.error,rv.error);if(rowError)setError(rowError);
  const todayIds=new Set(mealsOnDate(loadedMeals,todayISODate()).map(m=>m.id));
  setRsvps(r.data||[]);setAllergyRows(a.data||[]);setLate((l.data||[]).filter(x=>todayIds.has(x.meal_id)));setReviewRows(rv.data||[]);
 }
 useEffect(()=>{load()},[range.start.toISOString(),range.end.toISOString()]);
 const count=(id:string)=>rsvps.filter(r=>r.meal_id===id&&r.attending).length;
 const todayMeals=useMemo(()=>mealsOnDate(meals,todayISODate()),[meals]);
 const conflicts=useMemo(()=>meals.map(m=>{const attending=new Set(rsvps.filter(r=>r.meal_id===m.id&&r.attending).map(r=>r.user_id));const matches=allergyRows.filter(a=>attending.has(a.user_id)&&m.allergens?.includes(a.allergen));return{...m,count:new Set(matches.map(x=>x.user_id)).size,allergens:[...new Set(matches.map(x=>x.allergen))]}}).filter(m=>m.count>0),[meals,rsvps,allergyRows]);
 const reviewCount=(id:string)=>reviewRows.filter(r=>r.meal_id===id).length;
 const overallMealIds=useMemo(()=>meals.map(m=>m.id),[meals]);
 function startEdit(m:Meal){setEditing(m.id);setDrafts(x=>({...x,[m.id]:{...m,allergens:[...(m.allergens||[])]}}))}
 function cancelEdit(id:string){setEditing(null);setDrafts(x=>{const n={...x};delete n[id];return n})}
 function changeDraft(id:string,field:keyof Meal,value:any){setDrafts(x=>x[id]?{...x,[id]:{...x[id],[field]:value}}:x)}
 async function saveMeal(id:string){const d=drafts[id];if(!d||saving)return;setSaving(id);setError("");const payload={name:d.name.trim(),description:(d.description||"").trim(),allergens:[...(d.allergens||[])],updated_at:new Date().toISOString()};const{error:e}=await supabase.from("meals").update(payload).eq("id",id);if(e){setError(e.message);setSaving(null);return}setMeals(x=>sortMeals(x.map(m=>m.id===id?{...m,...payload}:m)));cancelEdit(id);setSaving(null)}
 async function updateLate(id:string,status:string){const{error:e}=await supabase.from("late_plates").update({status}).eq("id",id);if(e)setError(e.message);else setLate(x=>x.map(l=>l.id===id?{...l,status}:l))}
 async function signOut(){await supabase.auth.signOut()}
 const days=useMemo(()=>eachDay(range.start,range.end),[range]);
 const mealFor=(d:Date)=>mealsOnDate(meals,d);
 const renderCalendarMeal=(m:Meal)=><article className={`calendarMeal chefMealCard ${editing===m.id?"isEditing":""}`}key={m.id}>{editing===m.id?<div className="chefInlineEditor"><div className="chefMealMeta"><span>{m.meal_type}</span><span>{count(m.id)} attending</span></div><input value={drafts[m.id]?.name||""}onChange={e=>changeDraft(m.id,"name",e.target.value)}placeholder="Meal name"/><textarea value={drafts[m.id]?.description||""}onChange={e=>changeDraft(m.id,"description",e.target.value)}placeholder="Description"rows={2}/><div className="chefAllergenPicker">{ALLERGENS.map(a=><label key={a}><input type="checkbox" checked={drafts[m.id]?.allergens?.includes(a)||false}onChange={()=>{const current=drafts[m.id]?.allergens||[];changeDraft(m.id,"allergens",current.includes(a)?current.filter(x=>x!==a):[...current,a])}}/>{a}</label>)}</div><div className="chefEditorActions"><button className="chefSaveButton"onClick={()=>saveMeal(m.id)}disabled={saving===m.id}>{saving===m.id?"Saving…":"Save changes"}</button><button className="chefCancelButton"onClick={()=>cancelEdit(m.id)}disabled={saving===m.id}>Cancel</button></div></div>:<><div className="chefMealTop"><div><small>{m.meal_type}</small><h3>{m.name}</h3><MealRatingSummary mealIds={overallMealIds} mealId={m.id}/></div><strong>{count(m.id)}</strong></div>{m.description&&<p>{m.description}</p>}{m.allergens?.length>0&&<small>⚠️ {m.allergens.join(", ")}</small>}<div className="chefMealFooter"><span>{count(m.id)} attending · {reviewCount(m.id)} ratings</span><button className="chefEditButton"onClick={()=>startEdit(m)}>✎ Edit meal</button></div></>}</article>;
 const headcountDays=useMemo(()=>{const map=new Map<string,Meal[]>();sortMeals(meals).filter(m=>count(m.id)>0).forEach(m=>{if(!map.has(m.meal_date))map.set(m.meal_date,[]);map.get(m.meal_date)!.push(m)});return[...map.entries()].sort(([a],[b])=>a.localeCompare(b))},[meals,rsvps]);
 return <section className="roleWorkspace chefWorkspace"><header className="roleHero"><span>CHEF</span><h1>Good morning, Chef</h1><p>{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</p><button onClick={signOut}>Sign out</button></header><nav className="workspaceNav">{[["dashboard","Today"],["menu","Menu"],["alerts","Alerts"],["headcount","Headcounts"],["late","Late Plates"],["announce","Notify"],["print","Print"]].map(([k,l])=><button key={k}className={tab===k?"active":""}onClick={()=>setTab(k)}>{l}{k==="alerts"&&conflicts.length?` ${conflicts.length}`:""}</button>)}</nav>{error&&<div className="error">{error}</div>}
 {tab==="dashboard"&&<section className="chefIOSHome"><div className="chefTodayHero"><span>TODAY</span><h2>{todayMeals.length?"Kitchen at a glance":"No meals scheduled"}</h2><p>{todayMeals.length?`${todayMeals.length} meals today · Lunch first, Dinner second`:"No lunch or dinner scheduled for today."}</p></div><div className="chefMealTodayList">{todayMeals.map(m=><article className="todayMealCard"key={m.id}><div><span>{m.meal_type}</span><h3>{m.name}</h3><p>{m.description||"Menu item"}</p></div><div className="todayMealCount"><b>{count(m.id)}</b><small>eating</small></div><button onClick={()=>{setTab("menu");setMonth(parseMealDate(m.meal_date))}}>Edit</button></article>)}{!todayMeals.length&&<div className="chefEmpty">Your kitchen is clear today.</div>}</div><div className="chefStatusRow"><button onClick={()=>setTab("headcount")}><b>{rsvps.filter(r=>r.attending).length}</b><span>Going</span></button><button className="orange"onClick={()=>setTab("late")}><b>{late.filter(l=>l.status==="requested").length}</b><span>Late plates</span></button><button className="red"onClick={()=>setTab("alerts")}><b>{conflicts.length}</b><span>Allergy alerts</span></button></div><div className="chefSectionTitle">UPCOMING LUNCH & DINNER</div><div className="chefTimeline">{sortMeals(meals).slice(0,8).map(m=><article key={m.id}><div className="chefTimelineTime"><b>{m.meal_type}</b><span>{formatMealDate(m.meal_date,{month:"short",day:"numeric"})}</span></div><div className="chefTimelineLine"/><div className="chefTimelineMeal"><h3>{m.name}</h3><p>{count(m.id)} members · {m.description||"Menu item"}</p></div></article>)}</div></section>}
 {tab==="menu"&&<section className="panel monthCalendar chefMonthCalendar"><div className="heading"><div><h2>{formatMonthLabel(month)}</h2><p>Lunch & Dinner</p><MealRatingSummary mealIds={overallMealIds}/></div><div className="calendarActions"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><button onClick={()=>setMonth(monthBounds(new Date()).start)}>Today</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></div><div className="calendarGrid monthGrid"><div className="calendarHeader">Sun</div><div className="calendarHeader">Mon</div><div className="calendarHeader">Tue</div><div className="calendarHeader">Wed</div><div className="calendarHeader">Thu</div><div className="calendarHeader">Fri</div><div className="calendarHeader">Sat</div>{days.map(d=>{const ds=toISODate(d),outside=d.getMonth()!==month.getMonth(),isToday=ds===todayISODate();return <div className={`calendarCell ${outside?"outsideMonth":""} ${isToday?"today":""}`}key={ds}><div className="calendarDate">{d.getDate()}</div>{mealFor(d).map(renderCalendarMeal)}</div>})}</div></section>}
 {tab==="alerts"&&<section className="panel"><h2>Allergy Alerts</h2><p>Review conflicts before service.</p>{conflicts.length?conflicts.map(c=><article className="error"key={c.id}><b>{c.meal_date} · {c.meal_type} — {c.name}</b><span>{c.count} attending member(s) match: {c.allergens.join(", ")}</span></article>):<div className="message">No current RSVP allergy conflicts.</div>}</section>}
 {tab==="headcount"&&<section className="panel headcountPanel"><div className="heading"><div><h2>Headcounts</h2><p>Confirmed diners by day.</p></div><strong className="headcountTotal">{rsvps.filter(r=>r.attending).length} total RSVPs</strong></div>{headcountDays.map(([date,dayMeals])=><section className="headcountDay"key={date}><div className="headcountDayHeader"><b>{formatMealDate(date,{weekday:"long",month:"short",day:"numeric"})}</b><strong>{dayMeals.reduce((s,m)=>s+count(m.id),0)} total</strong></div>{dayMeals.map(m=><div className="headcountLine"key={m.id}><div><b>{m.name}</b><small>{m.meal_type}</small></div><strong>{count(m.id)}</strong></div>)}</section>)}{!headcountDays.length&&<div className="message">No confirmed RSVPs yet.</div>}</section>}
 {tab==="late"&&<section className="panel"><h2>Late Plates</h2><p>Today's active requests only.</p>{late.length?late.map(l=><div className="roleCard"key={l.id}><b>{meals.find(m=>m.id===l.meal_id)?.name||"Meal"}</b><span>{l.status}</span>{l.status==="requested"&&<button onClick={()=>updateLate(l.id,"preparing")}>Start preparing</button>}{l.status==="preparing"&&<button onClick={()=>updateLate(l.id,"ready")}>Ready</button>}{l.status==="ready"&&<button onClick={()=>updateLate(l.id,"picked_up")}>Picked up</button>}</div>):<div className="message">No active late-plate requests for today.</div>}</section>}
 {tab==="announce"&&<section className="panel"><AnnouncementForm heading="Notify Members"/></section>}
 {tab==="print"&&<section className="panel printSheet"><MonthlyPrintCalendar month={month} meals={meals} count={count} late={late}/></section>}
 </section>;
}
