import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
const allergens=["Milk","Eggs","Wheat","Soy","Peanuts","Tree Nuts","Fish","Shellfish","Sesame"];
const iso=(d:Date)=>d.toISOString().slice(0,10); const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1); const calendarStart=(d:Date)=>{const x=monthStart(d);x.setDate(x.getDate()-x.getDay());return x}; const calendarEnd=(d:Date)=>{const x=new Date(d.getFullYear(),d.getMonth()+1,0);x.setDate(x.getDate()+(6-x.getDay()));return x};
type Props={user:any;profile:any}; type Meal={id:string;meal_date:string;meal_type:string;name:string;description:string;allergens:string[]};
export default function ChefPage({user,profile}:Props){
 const [meals,setMeals]=useState<Meal[]>([]),[rsvps,setRsvps]=useState<any[]>([]),[allergyRows,setAllergyRows]=useState<any[]>([]),[late,setLate]=useState<any[]>([]),[tab,setTab]=useState("dashboard"),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState(""); const [announcementTitle,setAnnouncementTitle]=useState(""),[announcementMessage,setAnnouncementMessage]=useState(""),[announcementStatus,setAnnouncementStatus]=useState(""); const [month,setMonth]=useState(()=>monthStart(new Date())); const [editing,setEditing]=useState<string|null>(null); const [drafts,setDrafts]=useState<Record<string,Meal>>({}); const rangeStart=useMemo(()=>calendarStart(month),[month]),rangeEnd=useMemo(()=>calendarEnd(month),[month]);
 async function load(){const {data:menu}=await supabase.from("menus").select("id").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(menu){const {data,e}=await supabase.from("meals").select("id,meal_date,meal_type,name,description,allergens").eq("menu_id",menu.id).gte("meal_date",iso(rangeStart)).lte("meal_date",iso(rangeEnd)).order("meal_date").order("meal_type");if(e)setError(e.message);setMeals(data||[])}else setMeals([]);const [r,a,l]=await Promise.all([supabase.from("rsvps").select("meal_id,user_id,attending"),supabase.from("member_allergies").select("user_id,allergen"),supabase.from("late_plates").select("id,meal_id,user_id,status,created_at").neq("status","cancelled")]);setRsvps(r.data||[]);setAllergyRows(a.data||[]);setLate(l.data||[])} useEffect(()=>{load()},[rangeStart.toISOString(),rangeEnd.toISOString()]);
 const count=(id:string)=>rsvps.filter(r=>r.meal_id===id&&r.attending).length; const conflicts=useMemo(()=>meals.map(m=>{const attending=new Set(rsvps.filter(r=>r.meal_id===m.id&&r.attending).map(r=>r.user_id));const matches=allergyRows.filter(a=>attending.has(a.user_id)&&m.allergens?.includes(a.allergen));return {...m,count:new Set(matches.map(x=>x.user_id)).size,allergens:[...new Set(matches.map(x=>x.allergen))]}}).filter(m=>m.count>0),[meals,rsvps,allergyRows]);
 function startEdit(m:Meal){setEditing(m.id);setDrafts(x=>({...x,[m.id]:{...m,allergens:[...(m.allergens||[])]}}))} function cancelEdit(id:string){setEditing(null);setDrafts(x=>{const n={...x};delete n[id];return n})} function changeDraft(id:string,field:keyof Meal,value:any){setDrafts(x=>({...x,[id]:{...x[id], [field]:value}}))}
 async function saveMeal(id:string){const d=drafts[id];if(!d)return;setSaving(id);setError("");const {error:e}=await supabase.from("meals").update({name:d.name,description:d.description,allergens:d.allergens,updated_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else{setMeals(x=>x.map(m=>m.id===id?d:m));cancelEdit(id)}setSaving(null)}
 async function updateLate(id:string,status:string){const {error:e}=await supabase.from("late_plates").update({status}).eq("id",id);if(e)setError(e.message);else setLate(x=>x.map(l=>l.id===id?{...l,status}:l))} async function sendAnnouncement(){setAnnouncementStatus("");const title=announcementTitle.trim(),message=announcementMessage.trim();if(!title||!message){setAnnouncementStatus("Title and message are required.");return}const {data,error:e}=await supabase.rpc("send_member_announcement",{p_title:title,p_message:message,p_type:"announcement"});if(e){setAnnouncementStatus(e.message);return}setAnnouncementStatus(`${data||0} members notified.`);setAnnouncementTitle("");setAnnouncementMessage("")} async function signOut(){await supabase.auth.signOut()}
 const days=useMemo(()=>{const out=[];for(let d=new Date(rangeStart);d<=rangeEnd;d.setDate(d.getDate()+1))out.push(new Date(d));return out},[rangeStart,rangeEnd]); const mealFor=(d:Date)=>meals.filter(m=>m.meal_date===iso(d));
 const renderCalendarMeal=(m:Meal)=><article className={`calendarMeal chefMealCard ${editing===m.id?"isEditing":""}`} key={m.id}>{editing===m.id?<div className="chefInlineEditor"><div className="chefMealMeta"><span>{m.meal_type}</span><span>{count(m.id)} attending</span></div><input value={drafts[m.id]?.name||""} onChange={e=>changeDraft(m.id,"name",e.target.value)} placeholder="Meal name"/><textarea value={drafts[m.id]?.description||""} onChange={e=>changeDraft(m.id,"description",e.target.value)} placeholder="Description" rows={2}/><div className="chefAllergenPicker">{allergens.map(a=><label key={a}><input type="checkbox" checked={drafts[m.id]?.allergens?.includes(a)||false} onChange={()=>changeDraft(m.id,"allergens",drafts[m.id].allergens?.includes(a)?drafts[m.id].allergens.filter(x=>x!==a):[...(drafts[m.id].allergens||[]),a])}/>{a}</label>)}</div><div className="chefEditorActions"><button onClick={()=>saveMeal(m.id)} disabled={saving===m.id}>{saving===m.id?"Saving…":"Save"}</button><button onClick={()=>cancelEdit(m.id)}>Cancel</button></div></div>:<><div className="chefMealTop"><div><small>{m.meal_type}</small><h3>{m.name}</h3></div><strong>{count(m.id)}</strong></div>{m.description&&<p>{m.description}</p>}{m.allergens?.length>0&&<small>⚠️ {m.allergens.join(", ")}</small>}<div className="chefMealFooter"><span>{count(m.id)} attending</span><button onClick={()=>startEdit(m)}>Edit</button></div></>}</article>;
 const headcountDays=useMemo(()=>{const map=new Map<string,Meal[]>();meals.filter(m=>count(m.id)>0).forEach(m=>{if(!map.has(m.meal_date))map.set(m.meal_date,[]);map.get(m.meal_date)!.push(m)});return [...map.entries()].sort(([a],[b])=>a.localeCompare(b))},[meals,rsvps]);
 return <section className="roleWorkspace chefWorkspace"><header className="roleHero"><span>{profile?.role?.toUpperCase()}</span><h1>Chef Dashboard</h1><p>Your shared monthly menu, ready to plan and edit.</p><button onClick={signOut}>Sign out</button></header><nav className="workspaceNav">{[["dashboard","🧑‍🍳 Dashboard"],["menu","📅 Menu & Calendar"],["alerts","⚠️ Allergy Alerts"],["headcount","👥 Headcounts"],["late","🥡 Late Plates"],["announce","🔔 Notify Members"],["print","🖨️ Print"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}{k==="alerts"&&conflicts.length?` (${conflicts.length})`:""}</button>)}</nav>{error&&<div className="error">{error}</div>}
 {tab==="dashboard"&&<section className="panel"><h2>Kitchen Overview</h2><div className="stats"><div><b>{meals.length}</b><span>Meals this month</span></div><div><b>{rsvps.filter(r=>r.attending).length}</b><span>RSVPs</span></div><div><b>{conflicts.length}</b><span>Allergy conflicts</span></div><div><b>{late.filter(l=>l.status==="requested").length}</b><span>Late plates</span></div></div></section>}
 {tab==="menu"&&<section className="panel monthCalendar chefMonthCalendar"><div className="heading"><div><h2>{month.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><p>Menu & calendar · tap any meal to edit it.</p></div><div className="calendarActions"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><button onClick={()=>setMonth(monthStart(new Date()))}>Today</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></div><div className="chefCalendarHint">Edit meals directly where they appear. Changes are shared with Members immediately after saving.</div><div className="calendarGrid monthGrid"><div className="calendarHeader">Sun</div><div className="calendarHeader">Mon</div><div className="calendarHeader">Tue</div><div className="calendarHeader">Wed</div><div className="calendarHeader">Thu</div><div className="calendarHeader">Fri</div><div className="calendarHeader">Sat</div>{days.map(d=>{const ds=iso(d),outside=d.getMonth()!==month.getMonth(),isToday=ds===iso(new Date());return <div className={`calendarCell ${outside?"outsideMonth":""} ${isToday?"today":""}`} key={ds}><div className="calendarDate">{d.getDate()}</div>{mealFor(d).map(renderCalendarMeal)}{mealFor(d).length===0&&<button className="emptyMealPrompt">+ Add meal</button>}</div>})}</div></section>}
 {tab==="alerts"&&<section className="panel"><h2>Allergy Alerts</h2>{conflicts.length?conflicts.map(c=><article className="error" key={c.id}><b>{c.meal_date} · {c.meal_type} — {c.name}</b><span>{c.count} attending member(s) match: {c.allergens.join(", ")}</span></article>):<div className="message">No current RSVP allergy conflicts.</div>}</section>}
 {tab==="headcount"&&<section className="panel headcountPanel"><div className="heading"><div><h2>Headcounts</h2><p>Confirmed diners by day.</p></div><strong className="headcountTotal">{rsvps.filter(r=>r.attending).length} total RSVPs</strong></div><div className="headcountList">{headcountDays.map(([date,dayMeals])=>{const total=dayMeals.reduce((sum,m)=>sum+count(m.id),0);return <section className="headcountDay" key={date}><div className="headcountDayHeader"><b>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</b><strong>{total} total</strong></div>{dayMeals.map(m=><div className="headcountLine" key={m.id}><div><b>{m.name}</b><small>{m.meal_type}</small></div><strong>{count(m.id)}</strong></div>)}</section>})}{!headcountDays.length&&<div className="message">No confirmed RSVPs yet.</div>}</div></section>}
 {tab==="late"&&<section className="panel"><h2>Late Plates</h2>{late.length?late.map(l=><div className="roleCard" key={l.id}><b>{meals.find(m=>m.id===l.meal_id)?.name||"Meal"}</b><span>{l.status}</span>{l.status==="requested"&&<div><button onClick={()=>updateLate(l.id,"approved")}>Approve</button><button onClick={()=>updateLate(l.id,"ready")}>Ready</button></div>}</div>):<div className="message">No active late-plate requests.</div>}</section>}
 {tab==="announce"&&<section className="panel"><h2>Notify Members</h2><p>Send an announcement to all Members.</p><input value={announcementTitle} onChange={e=>setAnnouncementTitle(e.target.value)} placeholder="Announcement title" /><textarea value={announcementMessage} onChange={e=>setAnnouncementMessage(e.target.value)} placeholder="Message for Members" rows={5}/><button onClick={sendAnnouncement}>Send notification</button>{announcementStatus&&<div className="message">{announcementStatus}</div>}</section>}
 {tab==="print"&&<section className="panel printSheet"><h2>Kitchen Sheet</h2><p>{new Date().toLocaleDateString()}</p>{meals.filter(m=>m.meal_date===iso(new Date())).map(m=><article key={m.id}><h3>{m.meal_type}: {m.name}</h3><p>{count(m.id)} attending · {late.filter(l=>l.meal_id===m.id).length} late plates</p>{m.allergens?.length>0&&<p>Allergens: {m.allergens.join(", ")}</p>}</article>)}<button onClick={()=>window.print()}>Print Kitchen Sheet</button></section>}
 </section>}
