import React,{useEffect,useMemo,useState}from"react";
import{Bell,CalendarDays,Clock3,ChevronRight,UserRound,Utensils,ArrowLeft,AlertTriangle}from"lucide-react";
import{supabase}from"../lib/supabase";
import"../member-v2.css";

type Tab="home"|"menu"|"late"|"alerts"|"profile";
type Meal={id:string;meal_date:string;meal_type:string;name:string;description?:string|null;allergens?:string[]|null};
type Notice={id:string;title:string;message:string;read:boolean;created_at:string};
const allergens=["Milk","Eggs","Wheat","Soy","Peanuts","Tree Nuts","Fish","Shellfish","Sesame"];
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const label=(s:string)=>new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});
const shortLabel=(s:string)=>new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"});

export default function MemberPageV2({user,profile}:{user:any;profile:any}){
 const[tab,setTab]=useState<Tab>("home"),[meals,setMeals]=useState<Meal[]>([]),[saved,setSaved]=useState<string[]>([]),[late,setLate]=useState<string[]>([]),[notes,setNotes]=useState<Notice[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const day=today();const first=(profile?.full_name||"Member").trim().split(/\s+/)[0]||"Member";
 async function load(){setLoading(true);setError("");try{const end=new Date(`${day}T12:00:00`);end.setDate(end.getDate()+13);const menu=await supabase.from("menus").select("id").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(menu.error)throw menu.error;let ms:Meal[]=[];if(menu.data){const r=await supabase.from("meals").select("id,meal_date,meal_type,name,description,allergens").eq("menu_id",menu.data.id).gte("meal_date",day).lte("meal_date",end.toISOString().slice(0,10)).order("meal_date").order("meal_type");if(r.error)throw r.error;ms=(r.data||[])as Meal[]}const[a,l,n]=await Promise.all([supabase.from("member_allergies").select("allergen").eq("user_id",user.id),supabase.from("late_plates").select("meal_id").eq("user_id",user.id).neq("status","cancelled"),supabase.from("notifications").select("id,title,message,read,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50)]);if(a.error)throw a.error;if(l.error)throw l.error;if(n.error)throw n.error;setMeals(ms);setSaved((a.data||[]).map((x:any)=>x.allergen));setLate((l.data||[]).map((x:any)=>x.meal_id));setNotes((n.data||[])as Notice[])}catch(e:any){setError(e?.message||"We couldn't load your HouseEats data.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[user.id]);
 async function lateToggle(m:Meal){const active=late.includes(m.id);const r=active?await supabase.from("late_plates").update({status:"cancelled"}).eq("user_id",user.id).eq("meal_id",m.id).neq("status","cancelled"):await supabase.from("late_plates").insert({user_id:user.id,meal_id:m.id,status:"requested"});if(r.error)setError(r.error.message);else setLate(x=>active?x.filter(id=>id!==m.id):[...x,m.id])}
 async function allergyToggle(a:string){const active=saved.includes(a);const r=active?await supabase.from("member_allergies").delete().eq("user_id",user.id).eq("allergen",a):await supabase.from("member_allergies").insert({user_id:user.id,allergen:a});if(r.error)setError(r.error.message);else setSaved(x=>active?x.filter(v=>v!==a):[...x,a])}
 async function read(id:string){const r=await supabase.from("notifications").update({read:true}).eq("id",id).eq("user_id",user.id);if(!r.error)setNotes(x=>x.map(n=>n.id===id?{...n,read:true}:n))}
 async function readAll(){const r=await supabase.from("notifications").update({read:true}).eq("user_id",user.id).eq("read",false);if(!r.error)setNotes(x=>x.map(n=>({...n,read:true})))}
 const upcoming=useMemo(()=>meals.filter(m=>m.meal_date>=day),[meals,day]);const todayMeals=upcoming.filter(m=>m.meal_date===day);const featured=todayMeals[0]||upcoming[0];const unread=notes.filter(n=>!n.read).length;
 if(loading)return <main className="v2-app v2-loading-screen"><span>HOUSEEATS</span></main>;
 return <main className="v2-app">
  <header className="v2-header"><button className="v2-wordmark"onClick={()=>setTab("home")}><span>HOUSEEATS</span><small>Dining for the house</small></button><button className="v2-icon-button"onClick={()=>setTab("alerts")}aria-label="Alerts"><Bell/>{unread>0&&<b>{unread}</b>}</button></header>
  {error&&<div className="v2-error"><AlertTriangle/><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}
  {tab==="home"&&<section className="v2-home">
   <div className="v2-welcome"><span>WELCOME BACK</span><h1>{first}.</h1><p>Here’s what’s being served.</p></div>
   {featured?<section className="v2-dinner"><div className="v2-dinner-top"><span>{featured.meal_date===day?"TONIGHT":"COMING UP"}</span><time>{shortLabel(featured.meal_date)}</time></div><div className="v2-dinner-main"><div><h2>{featured.name}</h2><p>{featured.description||"Prepared fresh for the house."}</p></div><div className="v2-dish-mark"><Utensils/></div></div><button className="v2-dark-button"onClick={()=>setTab("menu")}>See the full menu<ChevronRight/></button></section>:<section className="v2-empty-feature"><CalendarDays/><h2>No menu posted yet.</h2><p>The kitchen hasn’t posted the next meals.</p></section>}
   <div className="v2-home-section"><div className="v2-section-title"><span>THE WEEK AHEAD</span><button onClick={()=>setTab("menu")}>View menu<ChevronRight/></button></div><div className="v2-week-list">{upcoming.slice(0,5).map(m=><button key={m.id}onClick={()=>setTab("menu")}><div><time>{shortLabel(m.meal_date)}</time><strong>{m.name}</strong></div><span>{m.meal_type}</span><ChevronRight/></button>)}</div></div>
   <div className="v2-home-actions"><button onClick={()=>setTab("late")}><Clock3/><div><strong>Late plate</strong><span>{late.length?"You have an active request":"Tell the kitchen you’ll be late"}</span></div><ChevronRight/></button><button onClick={()=>setTab("profile")}><AlertTriangle/><div><strong>Dietary information</strong><span>{saved.length?`${saved.length} dietary alert${saved.length===1?"":"s"} saved`:"Keep your kitchen profile up to date"}</span></div><ChevronRight/></button></div>
  </section>}
  {tab==="menu"&&<section className="v2-page"><PageTitle title="Menu" eyebrow="FROM THE KITCHEN" back={()=>setTab("home")}/><div className="v2-menu-list">{upcoming.map(m=>{const warning=(m.allergens||[]).some(a=>saved.includes(a));return <article key={m.id}className={m.meal_date===day?"is-today":""}><div className="v2-menu-date"><span>{m.meal_date===day?"TODAY":shortLabel(m.meal_date)}</span><b>{m.meal_type}</b></div><h2>{m.name}</h2>{m.description&&<p>{m.description}</p>}{warning&&<div className="v2-warning"><AlertTriangle/>Contains an ingredient in your dietary alerts.</div>}<button className={late.includes(m.id)?"requested":""}onClick={()=>lateToggle(m)}>{late.includes(m.id)?"Late plate requested":"Request a late plate"}</button></article>})}</div></section>}
  {tab==="late"&&<section className="v2-page"><PageTitle title="Late plate" eyebrow="MEAL SERVICE" subtitle="Let the kitchen know when you’ll miss dinner." back={()=>setTab("home")}/><div className="v2-late-list">{upcoming.map(m=><div key={m.id}><div><time>{shortLabel(m.meal_date)} · {m.meal_type}</time><strong>{m.name}</strong></div><button className={late.includes(m.id)?"requested":""}onClick={()=>lateToggle(m)}>{late.includes(m.id)?"Requested":"Request"}</button></div>)}</div></section>}
  {tab==="alerts"&&<section className="v2-page"><PageTitle title="Alerts" eyebrow="HOUSE UPDATES" subtitle="Messages from the kitchen and chapter." back={()=>setTab("home")}/>{unread>0&&<button className="v2-text-action"onClick={readAll}>Mark all as read</button>}<div className="v2-alert-list">{notes.length?notes.map(n=><button key={n.id}className={n.read?"":"unread"}onClick={()=>read(n.id)}><Bell/><div><strong>{n.title}</strong><p>{n.message}</p><time>{new Date(n.created_at).toLocaleDateString()}</time></div></button>):<div className="v2-empty">You’re all caught up.</div>}</div></section>}
  {tab==="profile"&&<section className="v2-page"><PageTitle title={profile?.full_name||"Member"} eyebrow="YOUR HOUSE PROFILE" subtitle={user?.email||""} back={()=>setTab("home")}/><div className="v2-profile"><div className="v2-profile-copy"><span>DIETARY INFORMATION</span><h2>Help the kitchen look after you.</h2><p>Select any ingredients you need to avoid. Your information is used for meal service.</p></div><div className="v2-allergy-grid">{allergens.map(a=><button key={a}className={saved.includes(a)?"selected":""}onClick={()=>allergyToggle(a)}>{a}<span>{saved.includes(a)?"✓":""}</span></button>)}</div></div></section>}
  <nav className="v2-nav"><Nav active={tab==="home"}label="Home"icon={<span className="v2-home-icon"/>}onClick={()=>setTab("home")}/><Nav active={tab==="menu"}label="Menu"icon={<Utensils/>}onClick={()=>setTab("menu")}/><Nav active={tab==="late"}label="Late plate"icon={<Clock3/>}onClick={()=>setTab("late")}/><Nav active={tab==="alerts"}label="Alerts"icon={<Bell/>}badge={unread}onClick={()=>setTab("alerts")}/><Nav active={tab==="profile"}label="Profile"icon={<UserRound/>}onClick={()=>setTab("profile")}/></nav>
 </main>
}
function PageTitle({eyebrow,title,subtitle,back}:{eyebrow:string;title:string;subtitle?:string;back:()=>void}){return <div className="v2-page-title"><button onClick={back}><ArrowLeft/>Back</button><span>{eyebrow}</span><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>}
function Nav({active,label,icon,badge,onClick}:{active:boolean;label:string;icon:React.ReactNode;badge?:number;onClick:()=>void}){return <button className={active?"active":""}onClick={onClick}>{icon}<span>{label}</span>{badge?<b>{badge}</b>:null}</button>}
