import React,{useEffect,useMemo,useState}from"react";
import{supabase}from"../lib/supabase";
import"./MemberV2Working.css";

type Props={user:any;profile:any};
type Meal={id:string;meal_date:string;meal_name:string;description?:string|null;start_time?:string|null;end_time?:string|null;location?:string|null};

export default function MemberV2Working({user,profile}:Props){const[meals,setMeals]=useState<Meal[]>([]);const[loading,setLoading]=useState(true);const[tab,setTab]=useState("home");const[name]=useState(profile?.full_name||user?.email?.split("@")[0]||"Member");
useEffect(()=>{let alive=true;(async()=>{const today=new Date();const start=new Date(today);start.setDate(today.getDate()-today.getDay());const end=new Date(start);end.setDate(start.getDate()+13);const{data}=await supabase.from("meals").select("id,meal_date,meal_name,description,start_time,end_time,location").gte("meal_date",start.toISOString().slice(0,10)).lte("meal_date",end.toISOString().slice(0,10)).order("meal_date",{ascending:true});if(alive)setMeals((data||[]) as Meal[]);setLoading(false)})();return()=>{alive=false}},[]);
const todayKey=new Date().toISOString().slice(0,10);const tonight=useMemo(()=>meals.find(m=>m.meal_date===todayKey)||meals[0],[meals,todayKey]);
function nav(next:string){setTab(next)}
return <main className="m2"><header className="m2-top"><div><div className="m2-brand">HOUSEEATS</div><h1>{tab==="home"?<>Good evening,<br/><i>{name}.</i></>:tab==="menu"?"The menu":tab==="late"?"Late plate":tab==="alerts"?"Updates":"Your profile"}</h1></div><button className="m2-initial" onClick={()=>nav("profile")}>{name.slice(0,1).toUpperCase()}</button></header>
{tab==="home"&&<section className="m2-home"><div className="m2-overline">{tonight?.meal_date===todayKey?"TONIGHT":"UP NEXT"}</div>{loading?<div className="m2-loading">Loading the kitchen’s menu…</div>:tonight?<><h2>{tonight.meal_name}</h2><p className="m2-description">{tonight.description||"Dinner is being prepared by the kitchen."}</p><div className="m2-meta">{tonight.start_time||"Dinner"}{tonight.location?` · ${tonight.location}`:""}</div></>:<><h2>Menu coming soon.</h2><p className="m2-description">Your kitchen hasn’t posted the next meal yet.</p></>}<button className="m2-link" onClick={()=>nav("menu")}>See the full menu <span>→</span></button><div className="m2-list"><button onClick={()=>nav("late")}><small>01</small><b>Late plate</b><span>Request dinner after hours →</span></button><button onClick={()=>nav("alerts")}><small>02</small><b>Updates</b><span>Chapter & kitchen notices →</span></button></div></section>}
{tab==="menu"&&<section className="m2-section"><div className="m2-overline">NEXT TWO WEEKS</div>{loading?<div className="m2-loading">Loading…</div>:meals.length?meals.map(m=><article className="m2-meal" key={m.id}><time>{new Date(m.meal_date+"T12:00:00").toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}</time><div><h2>{m.meal_name}</h2><p>{m.description||""}</p></div></article>):<h2>No meals posted yet.</h2>}</section>}
{tab==="late"&&<section className="m2-section"><div className="m2-overline">DINING SUPPORT</div><h2>Need your plate later?</h2><p className="m2-description">Let the kitchen know you’ll arrive after the normal meal service.</p><button className="m2-dark">Request a late plate</button></section>}
{tab==="alerts"&&<section className="m2-section"><div className="m2-overline">UPDATES</div><h2>You’re all caught up.</h2><p className="m2-description">New kitchen and chapter notices will appear here.</p></section>}
{tab==="profile"&&<section className="m2-section"><div className="m2-overline">ACCOUNT</div><h2>{name}</h2><p className="m2-description">{user?.email}</p><div className="m2-profile-row"><b>Dietary information</b><span>Manage in your allergy profile →</span></div></section>}
<nav className="m2-nav">{[["home","Home"],["menu","Menu"],["late","Late plate"],["alerts","Updates"],["profile","Profile"]].map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>nav(key)}>{label}</button>)}</nav></main>}
