import React, { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import NotificationCenter, { HouseNotification } from "../components/NotificationCenter";

const allergens=["Milk","Eggs","Wheat","Soy","Peanuts","Tree Nuts","Fish","Shellfish","Sesame"];
const iso=(d:Date)=>d.toISOString().slice(0,10); const startOfWeek=(d:Date)=>{const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return x}; const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
type Props={user:any;profile:any}; type Meal={id:string;meal_date:string;meal_type:string;name:string;description:string;allergens:string[]}; type Tab="home"|"menu"|"allergies"|"late"|"notifications"|"profile";
export default function MemberPage({user,profile}:Props){
 const [tab,setTab]=useState<Tab>("home"),[meals,setMeals]=useState<Meal[]>([]),[myAllergies,setMyAllergies]=useState<string[]>([]),[rsvps,setRsvps]=useState<Record<string,boolean>>({}),[late,setLate]=useState<string[]>([]),[notifications,setNotifications]=useState<HouseNotification[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[weekStart,setWeekStart]=useState(()=>startOfWeek(new Date()));
 const rangeStart=weekStart,rangeEnd=addDays(weekStart,13);
 async function load(){setLoading(true);setError("");const {data:menu}=await supabase.from("menus").select("id").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(menu){const {data,e}=await supabase.from("meals").select("id,meal_date,meal_type,name,description,allergens").eq("menu_id",menu.id).gte("meal_date",iso(rangeStart)).lte("meal_date",iso(rangeEnd)).order("meal_date").order("meal_type");if(e)setError(e.message);setMeals(data||[])}else setMeals([]);const [a,r,l,n]=await Promise.all([supabase.from("member_allergies").select("allergen").eq("user_id",user.id),supabase.from("rsvps").select("meal_id,attending").eq("user_id",user.id),supabase.from("late_plates").select("meal_id").eq("user_id",user.id).neq("status","cancelled"),supabase.from("notifications").select("id,type,title,message,read,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50)]);setMyAllergies((a.data||[]).map((x:any)=>x.allergen));setRsvps(Object.fromEntries((r.data||[]).map((x:any)=>[x.meal_id,x.attending])));setLate((l.data||[]).map((x:any)=>x.meal_id));setNotifications((n.data||[]) as HouseNotification[]);const firstError=[a.error,r.error,l.error,n.error].find(Boolean);if(firstError)setError(firstError.message);setLoading(false)}
 useEffect(()=>{load();const channel=supabase.channel(`member-notifications-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`user_id=eq.${user.id}`},()=>load()).subscribe();return()=>{supabase.removeChannel(channel)}},[user.id,rangeStart.toISOString(),rangeEnd.toISOString()]);
 async function toggleRsvp(meal_id:string){const attending=!rsvps[meal_id];const {error:e}=await supabase.from("rsvps").upsert({user_id:user.id,meal_id,attending,updated_at:new Date().toISOString()},{onConflict:"user_id,meal_id"});if(!e)setRsvps(x=>({...x,[meal_id]:attending}));else setError(e.message)}
 async function toggleAllergy(a:string){if(myAllergies.includes(a)){const {error:e}=await supabase.from("member_allergies").delete().eq("user_id",user.id).eq("allergen",a);if(!e)setMyAllergies(x=>x.filter(v=>v!==a));}else{const {error:e}=await supabase.from("member_allergies").insert({user_id:user.id,allergen:a});if(!e)setMyAllergies(x=>[...x,a]);}}
 async function requestLate(meal_id:string){if(late.includes(meal_id))return;const {error:e}=await supabase.from("late_plates").insert({user_id:user.id,meal_id,status:"requested"});if(!e)setLate(x=>[...x,meal_id]);else setError(e.message)}
 async function read(id:string){const {error:e}=await supabase.from("notifications").update({read:true}).eq("id",id).eq("user_id",user.id);if(!e)setNotifications(x=>x.map(n=>n.id===id?{...n,read:true}:n))} async function readAll(){const {error:e}=await supabase.from("notifications").update({read:true}).eq("user_id",user.id).eq("read",false);if(!e)setNotifications(x=>x.map(n=>({...n,read:true})))} async function signOut(){await supabase.auth.signOut()}
 const unread=notifications.filter(n=>!n.read).length;const today=iso(new Date());const todays=meals.filter(m=>m.meal_date===today); const days=useMemo(()=>Array.from({length:14},(_,i)=>addDays(weekStart,i)),[weekStart]);
 const renderMeal=(m:Meal)=><article className="mealCard memberWeekMeal" key={m.id}><div><small>{m.meal_type}</small><h3>{m.name}</h3>{m.description&&<p>{m.description}</p>}{m.allergens?.length>0&&<small>⚠️ {m.allergens.join(", ")}</small>}</div><div className="mealActions"><button onClick={()=>toggleRsvp(m.id)}>{rsvps[m.id]?"✓ Coming":"RSVP"}</button><button onClick={()=>requestLate(m.id)} disabled={late.includes(m.id)}>{late.includes(m.id)?"Late requested":"Late Plate"}</button></div></article>;
 const dayLabel=(d:Date)=>d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"});
 return <section className="roleWorkspace memberWorkspace"><header className="roleHero"><span>MEMBER</span><h1>Welcome, {profile?.full_name||"Member"}</h1><p>Your meals, allergies, late plates and notifications.</p><button onClick={signOut}>Sign out</button></header>
  <nav className="workspaceNav">{(["home","menu","allergies","late","notifications","profile"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="home"?"🏠 Home":x==="menu"?"📅 Meals":x==="allergies"?"⚠️ Allergies":x==="late"?"🥡 Late Plate":x==="notifications"?`🔔 Notifications${unread?` (${unread})`:""}`:"👤 Profile"}</button>)}</nav>
  {error&&<div className="error">{error}</div>}{loading?<div className="message">Loading HouseEats…</div>:<>
   {tab==="home"&&<section className="panel"><h2>Today's Meals</h2>{todays.length?todays.map(renderMeal):<div className="message">No meals posted for today.</div>}<h2>Next Meals</h2>{meals.filter(m=>m.meal_date>=today).slice(0,4).map(renderMeal)}</section>}
   {tab==="menu"&&<section className="panel memberTwoWeekMenu"><div className="heading"><div><h2>Meals</h2><p>This week & next week</p></div><div className="calendarActions"><button onClick={()=>setWeekStart(addDays(weekStart,-7))}>‹</button><button onClick={()=>setWeekStart(startOfWeek(new Date()))}>This week</button><button onClick={()=>setWeekStart(addDays(weekStart,7))}>›</button></div></div><div className="memberWeekList">{days.map(d=>{const ds=iso(d),dayMeals=meals.filter(m=>m.meal_date===ds),isToday=ds===today;return <section className={`memberWeekDay ${isToday?"today":""}`} key={ds}><header><div><b>{dayLabel(d)}</b>{isToday&&<span>Today</span>}</div><small>{dayMeals.length?`${dayMeals.length} meal${dayMeals.length===1?"":"s"}`:"No meals"}</small></header>{dayMeals.length?dayMeals.map(renderMeal):<div className="memberNoMeal">No meal scheduled</div>}</section>})}</div></section>}
   {tab==="allergies"&&<section className="panel"><h2>Allergies</h2><p>Select everything you need the kitchen to know about.</p><div className="allergyGrid">{allergens.map(a=><label key={a}><input type="checkbox" checked={myAllergies.includes(a)} onChange={()=>toggleAllergy(a)}/>{a}</label>)}</div><p><b>Selected:</b> {myAllergies.join(", ")||"None"}</p></section>}
   {tab==="late"&&<section className="panel"><h2>Late Plate</h2>{late.length?<div className="roleCards">{late.map(id=>{const m=meals.find(x=>x.id===id);return <div className="roleCard" key={id}><b>{m?.name||"Meal"}</b><small>{m?.meal_date} · {m?.meal_type}</small><span>Requested</span></div>})}</div>:<div className="message">You have no active late-plate requests. Request one from Meals.</div>}</section>}
   {tab==="notifications"&&<NotificationCenter notifications={notifications} onRead={read} onReadAll={readAll}/>} {tab==="profile"&&<section className="panel"><h2>Profile</h2><p><b>Name:</b> {profile?.full_name||"—"}</p><p><b>Email:</b> {profile?.email||user.email}</p><p><b>Role:</b> Member</p></section>}
  </>}</section>}
