import React,{useEffect,useMemo}from"react";
import{addDays,toISODate}from"../lib/calendar";

type Meal={id:string;meal_date:string;meal_type:string;name:string;description?:string;allergens?:string[]};
type Props={month:Date;meals:Meal[];count:(id:string)=>number;late:any[]};
const esc=(v:any)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");

export default function MonthlyPrintCalendar({month,meals,count,late}:Props){
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1,12);const start=new Date(first);start.setDate(1-first.getDay());const out:Date[]=[];for(let i=0;i<42;i++)out.push(addDays(start,i));return out},[month]);
 const mealFor=(d:Date)=>meals.filter(m=>m.meal_date===toISODate(d)).sort((a,b)=>a.meal_type.localeCompare(b.meal_type));
 const buildMarkup=()=>{const title=month.toLocaleDateString(undefined,{month:"long",year:"numeric"});const weekday=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const rows=Array.from({length:6},(_,w)=>`<tr>${days.slice(w*7,w*7+7).map(d=>{const outside=d.getMonth()!==month.getMonth();const entries=mealFor(d).map(m=>`<div class="meal"><div class="type">${esc(m.meal_type)}</div><strong>${esc(m.name)}</strong>${m.description?`<div class="desc">${esc(m.description)}</div>`:""}${m.allergens?.length?`<div class="allergens">⚠ ${esc(m.allergens.join(", "))}</div>`:""}<div class="stats">${count(m.id)} attending · ${late.filter(l=>l.meal_id===m.id).length} late</div></div>`).join("");return`<td class="${outside?"outside":""}"><div class="date">${d.getDate()}</div>${entries}</td>`}).join("")}</tr>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>HouseEats — ${esc(title)}</title><style>
@page{size:Letter landscape;margin:.18in}*{box-sizing:border-box}html,body{margin:0!important;padding:0!important;width:100%;height:100%;font-family:Arial,Helvetica,sans-serif;color:#241714;background:#fff}.sheet{width:100%;height:7.95in;display:flex;flex-direction:column}.title{text-align:center;height:.48in;flex:none}.brand{font-size:8px;font-weight:900;letter-spacing:2.5px;color:#7a1717}.title h1{font-size:19px;line-height:20px;margin:2px 0;color:#7a1717}.title p{font-size:7px;margin:0;color:#78675f}.cal{width:100%;height:7.42in;border-collapse:collapse;table-layout:fixed;flex:none}.cal thead{height:.24in}.cal th{height:.24in;padding:0;background:#7a1717;color:#fff;border:1px solid #7a1717;font-size:7px;text-transform:uppercase;letter-spacing:.5px}.cal tbody{height:7.18in}.cal tr{height:1.196in}.cal td{height:1.196in;vertical-align:top;border:1px solid #b7a69d;padding:3px;overflow:hidden}.cal td.outside{background:#f5f1ed}.date{font-size:9px;font-weight:900;color:#7a1717;margin-bottom:2px}.outside .date{color:#aaa09a}.meal{border-left:2px solid #d58b28;background:#fff7ed;border-radius:2px;padding:2px 3px;margin-bottom:2px;overflow:hidden}.type{font-size:4.5px;font-weight:900;text-transform:uppercase;letter-spacing:.45px;color:#9a6240}.meal strong{display:block;font-size:6.2px;line-height:1.05;margin-top:1px;white-space:normal;overflow-wrap:anywhere}.desc{font-size:4.5px;line-height:1.05;color:#665751;margin-top:1px;max-height:10px;overflow:hidden}.allergens{font-size:4.2px;line-height:1.05;color:#8a4b3a;margin-top:1px}.stats{font-size:4px;line-height:1.05;color:#78675f;margin-top:1px}.printHint{font-size:6px;color:#78675f;text-align:center;margin-top:2px}@media print{.printHint{display:none}}
</style></head><body><div class="sheet"><div class="title"><div class="brand">HOUSEEATS</div><h1>${esc(title)}</h1><p>Kitchen Monthly Menu</p></div><table class="cal"><thead><tr>${weekday.map(d=>`<th>${d}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><div class="printHint">Print at 100% scale · Letter · Landscape</div></div><script>window.onload=function(){window.focus();setTimeout(function(){window.print()},150)}</script></body></html>`};
 const printStandalone=()=>{const w=window.open("","_blank","width=1200,height=850");if(!w){alert("Please allow pop-ups for HouseEats to print the monthly menu.");return}w.document.open();w.document.write(buildMarkup());w.document.close()};
 useEffect(()=>{const original=window.print;window.print=printStandalone;return()=>{window.print=original}},[month,meals,rsvpsKey(meals),late]);
 return <div className="monthlyPrintDocument"><button className="standalonePrintButton" onClick={printStandalone}>Print Full Month</button></div>;
}
function rsvpsKey(meals:Meal[]){return meals.map(m=>m.id+":"+m.meal_date).join("|")}
