import React from "react";
import { addDays, toISODate } from "../lib/calendar";

type Meal = { id:string; meal_date:string; meal_type:string; name:string; description?:string; allergens?:string[] };
type Props = { month:Date; meals:Meal[]; count:(id:string)=>number; late:any[] };

export default function MonthlyPrintCalendar({month,meals,count,late}:Props){
  const first=new Date(month.getFullYear(),month.getMonth(),1,12);
  const last=new Date(month.getFullYear(),month.getMonth()+1,0,12);
  const start=new Date(first); start.setDate(first.getDate()-first.getDay());
  const days:Array<Date>=[]; for(let d=new Date(start);days.length<42;d=addDays(d,1)) days.push(new Date(d));
  const mealFor=(d:Date)=>meals.filter(m=>m.meal_date===toISODate(d)).sort((a,b)=>a.meal_type.localeCompare(b.meal_type));
  const buildMarkup=()=>{
    const title=month.toLocaleDateString(undefined,{month:"long",year:"numeric"});
    const cells=days.map(d=>{const outside=d.getMonth()!==month.getMonth();const entries=mealFor(d).map(m=>`<div class="meal"><b>${m.meal_type}</b><strong>${m.name}</strong>${m.description?`<span>${m.description}</span>`:""}${m.allergens?.length?`<small>⚠ ${m.allergens.join(", ")}</small>`:""}<em>${count(m.id)} attending · ${late.filter(l=>l.meal_id===m.id).length} late</em></div>`).join("");return `<td class="${outside?"outside":""}"><div class="date">${d.getDate()}</div>${entries}</td>`}).join("");
    return `<html><head><title>HouseEats — ${title} Menu</title><style>@page{size:letter landscape;margin:.18in}*{box-sizing:border-box}html,body{margin:0;padding:0;width:100%;height:100%;font-family:Arial,Helvetica,sans-serif;color:#241714}body{padding:0}.title{text-align:center;height:42px}.brand{font-size:8px;font-weight:900;letter-spacing:2px;color:#7a1717}.title h1{font-size:20px;line-height:20px;margin:2px 0;color:#7a1717}.title p{font-size:7px;margin:0;color:#78675f}.cal{width:100%;height:calc(100vh - 42px);border-collapse:collapse;table-layout:fixed}.cal th{height:20px;background:#7a1717;color:#fff;border:1px solid #7a1717;font-size:7px;text-transform:uppercase;letter-spacing:.4px}.cal td{height:calc((100% - 20px)/6);vertical-align:top;border:1px solid #a99a90;padding:3px;overflow:hidden}.cal td.outside{background:#f4f0ec;color:#aaa09a}.date{font-size:8px;font-weight:900;color:#7a1717;margin-bottom:2px}.outside .date{color:#aaa09a}.meal{border-left:2px solid #d58b28;background:#fff6ea;padding:2px 3px;margin-bottom:2px;overflow:hidden;line-height:1.05}.meal b{display:block;font-size:4.5px;text-transform:uppercase;letter-spacing:.4px;color:#9a6240}.meal strong{display:block;font-size:6px;line-height:1.05;margin-top:1px}.meal span{display:block;font-size:4.6px;line-height:1.05;color:#665751;margin-top:1px;max-height:11px;overflow:hidden}.meal small{display:block;font-size:4.2px;color:#8a4b3a;margin-top:1px}.meal em{display:block;font-size:4px;color:#78675f;font-style:normal;margin-top:1px}button{display:block;margin:0 auto 6px;padding:7px 18px;border:0;border-radius:5px;background:#7a1717;color:#fff;font-weight:700}@media print{button{display:none}.title{height:42px}.cal{height:calc(100vh - 42px)}}</style></head><body><div class="title"><div class="brand">HOUSEEATS</div><h1>${title}</h1><p>Kitchen Monthly Menu</p></div><table class="cal"><thead><tr>${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map(d=>`<th>${d}</th>`).join("")}</tr></thead><tbody>${Array.from({length:6},(_,w)=>`<tr>${cells.slice?days.slice(w*7,w*7+7).map(d=>{const outside=d.getMonth()!==month.getMonth();const entries=mealFor(d).map(m=>`<div class="meal"><b>${m.meal_type}</b><strong>${m.name}</strong>${m.description?`<span>${m.description}</span>`:""}${m.allergens?.length?`<small>⚠ ${m.allergens.join(", ")}</small>`:""}<em>${count(m.id)} attending · ${late.filter(l=>l.meal_id===m.id).length} late</em></div>`).join("");return `<td class="${outside?"outside":""}"><div class="date">${d.getDate()}</div>${entries}</td>`}).join(""):""}</tr>`).join("")}</tbody></table><button onclick="window.print()">Print</button></body></html>`;
  };
  function printStandalone(){const w=window.open("","_blank","width=1200,height=850");if(!w)return;w.document.open();w.document.write(buildMarkup());w.document.close();setTimeout(()=>{w.focus();w.print()},250)}
  return <div className="monthlyPrintDocument"><button className="standalonePrintButton" onClick={printStandalone}>Print Full Month</button></div>;
}
