import React,{useMemo}from"react";
import{formatMonthLabel,monthGridDays}from"../lib/calendar";
import{mealsOnDate}from"../lib/meals";
type Meal={id:string;meal_date:string;meal_type:string;name:string;description?:string;allergens?:string[]};
type Props={month:Date;meals:Meal[];count:(id:string)=>number;late:any[]};
const esc=(v:any)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
export default function MonthlyPrintCalendar({month,meals}:Props){
 const days=useMemo(()=>monthGridDays(month),[month]);
 const mealFor=(d:Date)=>mealsOnDate(meals,d);
 const build=()=>{const title=formatMonthLabel(month);const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];const cells=days.map(d=>{const outside=d.getMonth()!==month.getMonth();const mealsHtml=mealFor(d).map(m=>`<div class="meal"><b>${esc(m.meal_type)}</b><strong>${esc(m.name)}</strong>${m.description?`<span>${esc(m.description)}</span>`:""}${m.allergens?.length?`<small>⚠ ${esc(m.allergens.join(", "))}</small>`:""}</div>`).join("");return`<div class="cell ${outside?"outside":""}"><div class="date">${d.getDate()}</div>${mealsHtml}</div>`}).join("");return`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)} Menu</title><style>@page{size:letter landscape;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;width:11in;height:8.5in;font-family:Arial,sans-serif;color:#241714}body{overflow:hidden}.page{width:11in;height:8.5in;padding:.18in;display:flex;flex-direction:column;overflow:hidden}.head{height:.55in;flex:none;text-align:center;overflow:hidden}.brand{font-size:8pt;font-weight:900;letter-spacing:2px;color:#7a1717}.head h1{font-size:18pt;line-height:20pt;margin:1px 0;color:#7a1717}.head p{font-size:7pt;margin:0;color:#78675f}.week{height:.24in;display:grid;grid-template-columns:repeat(7,1fr);flex:none}.week div{background:#7a1717;color:#fff;border:1px solid #7a1717;text-align:center;font-size:6.5pt;font-weight:700;padding:4px 0}.grid{height:7.35in;display:grid;grid-template-columns:repeat(7,1fr);grid-template-rows:repeat(6,1fr);min-height:0;overflow:hidden}.cell{min-width:0;min-height:0;border:1px solid #ad9c92;padding:3px;overflow:hidden}.outside{background:#f3efeb;color:#aaa09a}.date{font-size:8pt;font-weight:900;color:#7a1717;margin-bottom:2px}.outside .date{color:#aaa09a}.meal{border-left:2px solid #d58b28;background:#fff6ea;padding:2px 3px;margin-bottom:2px;overflow:hidden}.meal b{display:block;font-size:4.5pt;text-transform:uppercase;color:#9a6240}.meal strong{display:block;font-size:6pt;line-height:6.5pt;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meal span,.meal small{display:block;font-size:4.5pt;line-height:5pt;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meal small{color:#8a4b3a}@media print{html,body{width:11in!important;height:8.5in!important;overflow:hidden!important}.page{width:11in!important;height:8.5in!important}.grid{height:7.35in!important;grid-template-rows:repeat(6,1fr)!important}.cell,.meal{break-inside:avoid!important;page-break-inside:avoid!important}}</style></head><body><div class="page"><div class="head"><div class="brand">HOUSEEATS</div><h1>${esc(title)}</h1><p>Kitchen Monthly Menu</p></div><div class="week">${names.map(n=>`<div>${n}</div>`).join("")}</div><div class="grid">${cells}</div></div><script>window.onload=()=>setTimeout(()=>window.print(),200)</script></body></html>`};
 const print=()=>{const w=window.open("","_blank","width=1200,height=850");if(!w){alert("Please allow pop-ups to print the monthly menu.");return}w.document.write(build());w.document.close()};
 return <button className="monthlyPrintButton" type="button" onClick={print} style={{display:"inline-flex",alignItems:"center",justifyContent:"center",padding:"12px 20px",border:0,borderRadius:10,background:"#7a1717",color:"#fff",fontWeight:800,cursor:"pointer"}}>Print Full Month</button>;
}
