import "./v2.css";
import "./v2-parity.css";
import "./v2-overhaul.css";
import "./v2-premium.css";
import "./v2-admin.css";
import "./v2-parity-tools.css";
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
