import "./index.css";
import React,{useEffect,useMemo,useState} from "react";
import ReactDOM from "react-dom/client";
import {supabase} from "./lib/supabase";

type Page="dashboard"|"menu"|"allergies"|"late"|"notifications"|"chef";
type Meal={id:string;date:string;week:number;day:string;type:"Lunch"|"Dinner";name:string;description:string;allergens:string[];menu_id:string};
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const allergens=["Milk","Eggs","Wheat","Soy","Peanuts","Tree Nuts","Fish","Shellfish","Sesame"];
const staffRoles=["admin","chef","moderator"];
const mondayOf=(d:Date)=>{const x=new Date(d),n=x.getDay();x.setDate(x.getDate()+(n===0?-6:1-n));x.setHours(0,0,0,0);return x};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const iso=(d:Date)=>d.toISOString().slice(0,10); const pretty=(d:Date)=>d.toLocaleDateString(undefined,{month:"short",day:"numeric"});
function Login({onLogin}:{onLogin:()=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{if(signup){const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;setSignup(false)}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;onLogin()}}catch(e:any){setError(e?.message||"Unable to sign in")}finally{setBusy(false)}}return <main className="loginPage"><div className="loginShell"><div className="loginBrand"><div className="brandMark">🍽️</div><div><div className="brandName">HouseEats</div><div className="brandTag">Better meals. Better organized.</div></div></div><div className="loginCard"><div className="loginIntro"><span className="eyebrow">MEMBER PORTAL</span><h1>{signup?"Welcome to HouseEats":"Welcome back"}</h1><p>{signup?"Create your account to view meals, RSVP, and manage allergies.":"Sign in to see your 4-week menu and manage your meals."}</p></div><form onSubmit={submit}>{signup&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Signing in…":signup?"Create My Account":"Sign In"}</button></form><button className="linkButton" onClick={()=>{setSignup(!signup);setError("")}}>{signup?"Already have an account? Sign in":"New to HouseEats? Create an account"}</button></div></div></main>}
function App(){
const[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>(null),[loading,setLoading]=useState(true),[profileError,setProfileError]=useState(""),[page,setPage]=useState<Page>("dashboard"),[periodOffset,setPeriodOffset]=useState(0),[meals,setMeals]=useState<Meal[]>([]),[myAllergies,setMyAllergies]=useState<string[]>([]),[rsvps,setRsvps]=useState<Record<string,boolean>>({}),[late,setLate]=useState<string[]>([]),[staffAllergies,setStaffAllergies]=useState<any[]>([]),[staffRsvps,setStaffRsvps]=useState<any[]>([]),[staffLate,setStaffLate]=useState<any[]>([]),[newDate,setNewDate]=useState(iso(new Date())),[newType,setNewType]=useState<"lunch"|"dinner">("dinner"),[newName,setNewName]=useState(""),[newDescription,setNewDescription]=useState(""),[newAllergens,setNewAllergens]=useState<string[]>([]),[creating,setCreating]=useState(false),[saving,setSaving]=useState<string|null>(null);
const periodStart=useMemo(()=>addDays(mondayOf(new Date()),periodOffset*28),[periodOffset]); const isStaff=staffRoles.includes(String(profile?.role||"").toLowerCase().trim());
async function loadProfile(id:string){try{const{data,error}=await supabase.from("profiles").select("id,full_name,email,role").eq("id",id).maybeSingle();if(error)throw error;if(data){setProfile(data);return}const{data:c,error:ce}=await supabase.from("profiles").insert({id,email:user?.email||"",full_name:user?.user_metadata?.full_name||"",role:"member"}).select("id,full_name,email,role").single();if(ce)throw ce;setProfile(c)}catch(e:any){setProfileError(e?.message||"Could not load profile")}}
async function loadUser(){const{data}=await supabase.auth.getUser();if(data.user){setUser(data.user);await loadProfile(data.user.id)}setLoading(false)}
useEffect(()=>{loadUser();const{data:{subscription}}=supabase.auth.onAuthStateChange(async(_,s)=>{setUser(s?.user||null);if(s?.user)await loadProfile(s.user.id);else setProfile(null)});return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(user)loadData()},[user,periodStart,isStaff]);
async function loadData(){const start=iso(periodStart),end=iso(addDays(periodStart,27));const{data:menu}=await supabase.from("menus").select("id").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(menu){const{data:rows}=await supabase.from("meals").select("id,menu_id,meal_date,week_number,day_of_week,meal_type,name,description,allergens").eq("menu_id",menu.id).gte("meal_date",start).lte("meal_date",end).order("meal_date");setMeals((rows||[]).map((m:any)=>({id:m.id,date:m.meal_date,week:Math.floor((new Date(m.meal_date+"T00:00:00").getTime()-periodStart.getTime())/604800000)+1,day:days[(m.day_of_week||1)-1],type:m.meal_type==="dinner"?"Dinner":"Lunch",name:m.name||"No meal posted",description:m.description||"",allergens:m.allergens||[],menu_id:m.menu_id})))}const{data:a}=await supabase.from("member_allergies").select("allergen").eq("user_id",user.id);setMyAllergies((a||[]).map((x:any)=>x.allergen));const{data:r}=await supabase.from("rsvps").select("meal_id,attending").eq("user_id",user.id);setRsvps(Object.fromEntries((r||[]).map((x:any)=>[x.meal_id,x.attending])));const{data:l}=await supabase.from("late_plates").select("meal_id").eq("user_id",user.id).neq("status","cancelled");setLate((l||[]).map((x:any)=>x.meal_id));if(isStaff){const[a1,r1,l1]=await Promise.all([supabase.from("member_allergies").select("user_id,allergen"),supabase.from("rsvps").select("meal_id,user_id,attending"),supabase.from("late_plates").select("meal_id,user_id,status").neq("status","cancelled")]);setStaffAllergies(a1.data||[]);setStaffRsvps(r1.data||[]);setStaffLate(l1.data||[])}else{setStaffAllergies([]);setStaffRsvps([]);setStaffLate([])}}
async function toggleRsvp(id:string){const attending=!rsvps[id];const{error}=await supabase.from("rsvps").upsert({user_id:user.id,meal_id:id,attending,updated_at:new Date().toISOString()},{onConflict:"user_id,meal_id"});if(!error)setRsvps(x=>({...x,[id]:attending}));else alert(error.message)}
async function toggleAllergy(a:string){if(myAllergies.includes(a)){const{error}=await supabase.from("member_allergies").delete().eq("user_id",user.id).eq("allergen",a);if(!error)setMyAllergies(x=>x.filter(v=>v!==a))}else{const{error}=await supabase.from("member_allergies").insert({user_id:user.id,allergen:a});if(!error)setMyAllergies(x=>[...x,a])}}
async function requestLate(id:string){if(late.includes(id))return;const{error}=await supabase.from("late_plates").insert({user_id:user.id,meal_id:id,status:"requested"});if(!error)setLate(x=>[...x,id]);else alert(error.message)}
async function updateMeal(id:string,field:string,value:any){if(!isStaff)return;setSaving(id);const{error}=await supabase.from("meals").update({[field]:value,updated_at:new Date().toISOString()}).eq("id",id);if(!error)setMeals(x=>x.map(m=>m.id===id?{...m,[field]:value}:m));else alert(error.message);setSaving(null)}
async function createMeal(e:React.FormEvent){e.preventDefault();if(!isStaff)return;setCreating(true);try{let{data:menu}=await supabase.from("menus").select("id").eq("active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!menu){const{data:m,error}=await supabase.from("menus").insert({name:"HouseEats 4-Week Menu",start_date:iso(mondayOf(new Date())),active:true}).select("id").single();if(error)throw error;menu=m}const d=new Date(newDate+"T00:00:00"),day=d.getDay()||7,week=Math.floor((d.getTime()-mondayOf(d).getTime())/604800000)+1;const{data:m,error}=await supabase.from("meals").insert({menu_id:menu.id,week_number:week,day_of_week:day,meal_date:newDate,meal_type:newType,name:newName||"No meal posted",description:newDescription,allergens:newAllergens}).select("id,menu_id,meal_date,meal_type,name,description,allergens").single();if(error)throw error;setMeals(x=>[...x,{id:m.id,date:m.meal_date,week,day:days[day-1],type:newType==="dinner"?"Dinner":"Lunch",name:m.name,description:m.description||"",allergens:m.allergens||[],menu_id:m.menu_id}]);setNewName("");setNewDescription("");setNewAllergens([])}catch(e:any){alert(e?.message||"Could not add meal")}finally{setCreating(false)}}
const warnings=useMemo(()=>meals.filter(m=>m.allergens.some(a=>myAllergies.includes(a))),[meals,myAllergies]);
const allergyAlerts=useMemo(()=>meals.map(m=>{const ids=new Set(staffRsvps.filter(r=>r.meal_id===m.id&&r.attending).map(r=>r.user_id));const matches=staffAllergies.filter(a=>ids.has(a.user_id)&&m.allergens.includes(a.allergen));return {...m,affected:new Set(matches.map(a=>a.user_id)).size,matches:[...new Set(matches.map(a=>a.allergen))]}}).filter(x=>x.affected>0),[meals,staffAllergies,staffRsvps]);
const mealCounts=(id:string)=>{const r=staffRsvps.filter(x=>x.meal_id===id),lateCount=staffLate.filter(x=>x.meal_id===id).length;return{yes:r.filter(x=>x.attending).length,no:r.filter(x=>!x.attending).length,late:lateCount}};
async function signOut(){await supabase.auth.signOut()}
if(loading)return <main className="loginPage"><div className="loadingCard"><div className="brandMark">🍽️</div><h1>HouseEats</h1></div></main>;if(!user)return <Login onLogin={loadUser}/>;
return <main className="app"><header><div><h1>HouseEats</h1><p>Fraternity meal management</p></div><div className="user"><span>{profile?.full_name||user.email}</span><button onClick={signOut}>Sign out</button></div></header><nav>{(["dashboard","menu","allergies","late","notifications","chef"] as Page[]).map(p=><button key={p} onClick={()=>setPage(p)}>{p==="chef"?"Chef / Mod":p==="menu"?"4-Week Menu":p[0].toUpperCase()+p.slice(1)}</button>)}</nav>{profileError&&<div className="error"><b>Profile error</b><span>{profileError}</span></div>}
{page==="dashboard"&&<section className="panel"><h2>Dashboard</h2><div className="stats"><div><b>4</b><span>Weeks</span></div><div><b>{Object.values(rsvps).filter(Boolean).length}</b><span>My RSVPs</span></div><div><b>{warnings.length}</b><span>Allergy alerts</span></div><div><b>{late.length}</b><span>Late plates</span></div></div>{isStaff&&<div className={allergyAlerts.length?"error":"message"}><b>{allergyAlerts.length?"Allergy action needed":"Allergy check clear"}</b><span>{allergyAlerts.length?`${allergyAlerts.length} meal(s) have conflicts for attending members.`:"No current RSVP allergy conflicts."}</span></div>}<p>Calendar period: {pretty(periodStart)} – {pretty(addDays(periodStart,27))}</p></section>}
{page==="menu"&&<section className="panel"><div className="heading"><div><h2>4-Week Calendar</h2><p>{pretty(periodStart)} – {pretty(addDays(periodStart,27))}</p></div><div className="periodButtons"><button onClick={()=>setPeriodOffset(x=>x-1)}>← Previous</button><button onClick={()=>setPeriodOffset(0)}>Current</button><button onClick={()=>setPeriodOffset(x=>x+1)}>Next →</button><button onClick={()=>window.print()}>Print</button></div></div>{[1,2,3,4].map(w=><div className="calendarWeek" key={w}><div className="weekTitle"><h3>Week {w} · {pretty(addDays(periodStart,(w-1)*7))}</h3></div><div className="calendarGrid">{days.map((d,i)=><div className="calendarHeader" key={d}><b>{d}</b><span>{pretty(addDays(periodStart,(w-1)*7+i))}</span></div>)}{days.map(d=><div className="calendarCell" key={d}>{meals.filter(m=>m.week===w&&m.day===d).map(m=>{const warn=m.allergens.some(a=>myAllergies.includes(a));return <div className={warn?"calendarMeal warning":"calendarMeal"} key={m.id}><strong>{m.type}</strong><div className="mealName">{m.name}</div><small>{m.description}</small>{m.allergens.length>0&&<small>⚠ {m.allergens.join(", ")}</small>}{warn&&<span className="allergyTag">ALLERGY MATCH</span>}<div className="calendarActions"><button onClick={()=>toggleRsvp(m.id)}>{rsvps[m.id]?"✓ RSVP":"RSVP"}</button><button onClick={()=>requestLate(m.id)}>{late.includes(m.id)?"Late ✓":"Late Plate"}</button></div></div>})}</div>)}</div></div>)}</section>}
{page==="allergies"&&<section className="panel"><h2>Allergy & Dietary Profile</h2><div className="allergyGrid">{allergens.map(a=><label key={a}><input type="checkbox" checked={myAllergies.includes(a)} onChange={()=>toggleAllergy(a)}/> {a}</label>)}</div><p><b>Your profile:</b> {myAllergies.join(", ")||"No allergies selected"}</p></section>}
{page==="late"&&<section className="panel"><h2>Late Plate</h2>{late.length?<ul>{late.map(id=>{const m=meals.find(x=>x.id===id);return <li key={id}>{m?.date} — {m?.type}: {m?.name}</li>})}</ul>:<p>No late plates requested.</p>}</section>}
{page==="notifications"&&<section className="panel"><h2>Notifications</h2>{warnings.length?<div className="error"><b>Allergy warning</b><span>{warnings.length} current meal(s) match your allergies.</span></div>:<p>No current allergy notifications.</p>}</section>}
{page==="chef"&&<section className="panel chef"><div className="heading"><div><h2>Chef / Moderator</h2><p>Meals, RSVP totals, late plates and allergy safety.</p></div><button onClick={()=>window.print()}>🖨 Print Kitchen Sheet</button></div>{!isStaff?<div className="error"><b>Chef access required</b><span>Your role is {profile?.role||"not loaded"}.</span></div>:<><div className="chefAlertPanel"><div className="chefAlertHeader"><div><h3>🚨 Allergy Alerts</h3><p>Only members who RSVP “Going” are included.</p></div><strong>{allergyAlerts.length}</strong></div>{allergyAlerts.length===0?<div className="message">No allergy conflicts detected for attending members.</div>:<div className="alertList">{allergyAlerts.map(a=><div className="alertCard" key={a.id}><div><b>{a.date} · {a.type}</b><h4>{a.name}</h4><span>{a.affected} attending member{a.affected===1?"":"s"} affected · {a.matches.join(", ")}</span></div><span className="allergyTag">ACTION NEEDED</span></div>)}</div>}</div><div className="chefStats">{meals.map(m=>{const c=mealCounts(m.id);return <div className="chefMealSummary" key={m.id}><b>{m.date} · {m.type}</b><strong>{m.name}</strong><span>🟢 {c.yes} going · 🔴 {c.no} not going · 🥡 {c.late} late</span></div>})}</div><div className="chefCreate"><h3>Add a Meal</h3><form onSubmit={createMeal}><input type="date" value={newDate} onChange={e=>setNewDate(e.target.value)} required/><select value={newType} onChange={e=>setNewType(e.target.value as any)}><option value="lunch">Lunch</option><option value="dinner">Dinner</option></select><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Meal name" required/><input value={newDescription} onChange={e=>setNewDescription(e.target.value)} placeholder="Description"/><div className="allergyGrid">{allergens.map(a=><label key={a}><input type="checkbox" checked={newAllergens.includes(a)} onChange={()=>setNewAllergens(x=>x.includes(a)?x.filter(v=>v!==a):[...x,a])}/> {a}</label>)}</div><button className="primary" disabled={creating}>{creating?"Adding…":"Add Meal"}</button></form></div><h3>Current Meals</h3>{[1,2,3,4].map(w=><div className="chefWeek" key={w}><h3>Week {w}</h3>{meals.filter(m=>m.week===w).map(m=><div className="chefRow" key={m.id}><b>{m.date} {m.type}</b><input value={m.name} onChange={e=>updateMeal(m.id,"name",e.target.value)}/><input value={m.description} onChange={e=>updateMeal(m.id,"description",e.target.value)}/><input value={m.allergens.join(", ")} onChange={e=>updateMeal(m.id,"allergens",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/><span>{saving===m.id?"Saving…":"Saved"}</span></div>)}</div>)}</>}</section>}</main>}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
