import React,{useEffect,useState}from"react";
import{Bell,BookOpen,ChefHat,Check,ClipboardList,Megaphone,Printer,RefreshCw,ShieldAlert,Users,UtensilsCrossed,X}from"lucide-react";
import{supabase}from"./lib/supabase";
type Props={user:any;profile:any;onSignOut:()=>void};
type Member={id:string;full_name:string|null;role:string|null;chapter_id:string|null};
type Meal={id:string;name:string;meal_date:string|null;meal_type:string;allergens:string[]};
type Late={id:string;meal_id:string;member_id:string;status:string;requested_at:string;notes?:string|null};
const dateLabel=(d:string|null)=>d?new Date(d+"T12:00:00").toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}):"—";
export default function V2AdminWorkspaceClean({user,profile,onSignOut}:Props){
 const[tab,setTab]=useState("overview"),[members,setMembers]=useState<Member[]>([]),[meals,setMeals]=useState<Meal[]>([]),[late,setLate]=useState<Late[]>([]),[allergy,setAllergy]=useState<any[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);const[m,me,l,a]=await Promise.all([supabase.from("profiles").select("id,full_name,role,chapter_id").order("full_name"),supabase.from("meals").select("id,name,meal_date,meal_type,allergens").gte("meal_date",new Date().toISOString().slice(0,10)).order("meal_date").limit(100),supabase.from("late_plate_requests").select("id,meal_id,member_id,status,requested_at,notes").order("requested_at",{ascending:false}).limit(100),supabase.from("allergy_profiles").select("member_id,allergies,dietary_restrictions")]);setMembers(m.data||[]);setMeals(me.data||[]);setLate(l.data||[]);setAllergy(a.data||[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const membersOnly=members.filter(x=>x.role==="member"),chefs=members.filter(x=>x.role==="chef"),admins=members.filter(x=>["admin","super_admin"].includes(String(x.role))),openLate=late.filter(x=>x.status==="requested").length;
 const memberName=(id:string)=>members.find(x=>x.id===id)?.full_name||"Member";const mealName=(id:string)=>meals.find(x=>x.id===id)?.name||"Meal";
 return <div className="v2-admin clean-admin"><header className="v2-admin-top"><div className="v2-admin-brand"><div className="v2-mark"><UtensilsCrossed size={20}/></div><div><b>HouseEats</b><span>Tasteful Traditions · Admin</span></div></div><div className="v2-admin-actions"><button onClick={()=>void load()}aria-label="Refresh"><RefreshCw size={18}/></button><button onClick={onSignOut}>Sign out</button></div></header><main className="v2-admin-main"><div className="v2-admin-welcome"><span>ADMIN CONSOLE</span><h1>{profile?.full_name||"Administrator"}</h1><p>Chapter operations, members, kitchen activity and service exceptions.</p></div><nav className="v2-admin-tabs">{[["overview","Overview",ClipboardList],["members","Members",Users],["kitchen","Kitchen",ChefHat]].map(([id,label,Icon]:any)=><button key={id}className={tab===id?"active":""}onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}<button className={tab==="announcements"?"active":""}onClick={()=>setTab("announcements")}><Megaphone size={17}/>Announcements</button><button className={tab==="feedback"?"active":""}onClick={()=>setTab("feedback")}><BookOpen size={17}/>Feedback</button></nav>{message&&<div className="v2-admin-message">{message}<button onClick={()=>setMessage("")}><X size={14}/></button></div>}{loading?<section className="v2-admin-card">Loading chapter data…</section>:tab==="overview"?<Overview members={membersOnly.length}chefs={chefs.length}admins={admins.length}meals={meals.length}late={openLate}allergy={allergy.length}onTab={setTab}/>:tab==="members"?<Members members={members}setMessage={setMessage}reload={load}/>:tab==="kitchen"?<Kitchen meals={meals}late={late}memberName={memberName}mealName={mealName}/>:<section className="v2-admin-card"><h2>{tab==="announcements"?"Announcements":"Meal feedback"}</h2><p>Use the existing V2 workflow for this section.</p></section>}</main></div>;
}
function Overview(p:any){const cards=[["Members",p.members,Users,"members"],["Chefs",p.chefs,ChefHat,"members"],["Upcoming meals",p.meals,UtensilsCrossed,"kitchen"],["Open service exceptions",p.late,ShieldAlert,"kitchen"],["Allergy profiles",p.allergy,ShieldAlert,"kitchen"]];return <div className="v2-admin-grid">{cards.map(([label,value,Icon,tab]:any)=><button key={label}className="v2-admin-stat"onClick={()=>p.onTab(tab)}><Icon size={20}/><span>{label}</span><b>{value}</b></button>)}</div>}
function Members({members,setMessage,reload}:any){const change=async(id:string,role:string)=>{const{error}=await supabase.from("profiles").update({role}).eq("id",id);setMessage(error?.message||"Role updated.");if(!error)void reload()};return <section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>PEOPLE</span><h2>Member management</h2></div><Users size={20}/></div><div className="v2-admin-list">{members.map((m:Member)=><div className="v2-admin-row"key={m.id}><div className="person-avatar">{(m.full_name||"?").slice(0,1).toUpperCase()}</div><div className="person-copy"><b>{m.full_name||"Unnamed member"}</b><small>{m.role||"member"}</small></div><select value={m.role||"member"}onChange={e=>void change(m.id,e.target.value)}><option value="member">Member</option><option value="chef">Chef</option><option value="admin">Admin</option></select></div>)}</div></section>}
function Kitchen({meals,late,memberName,mealName}:{meals:Meal[];late:Late[];memberName:(id:string)=>string;mealName:(id:string)=>string}){const today=new Date().toISOString().slice(0,10);return <><section className="v2-admin-grid"><div className="v2-admin-stat"><UtensilsCrossed/><span>Today's meals</span><b>{meals.filter(m=>m.meal_date===today).length}</b></div><div className="v2-admin-stat"><ShieldAlert/><span>Open service exceptions</span><b>{late.filter(x=>x.status==="requested").length}</b></div><div className="v2-admin-stat"><ShieldAlert/><span>Allergy profiles</span><b>—</b></div></section><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>UPCOMING MENU</span><h2>Kitchen schedule</h2></div><button onClick={()=>window.print()}><Printer size={17}/></button></div>{meals.length?meals.slice(0,40).map(m=><div className="v2-admin-row"key={m.id}><div><b>{m.name}</b><small>{dateLabel(m.meal_date)} · {m.meal_type}</small></div>{m.allergens?.length?<span className="risk-pill">{m.allergens.length} allergens</span>:<span>Clear</span>}</div>):<p>No upcoming meals.</p>}</section><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>SERVICE EXCEPTIONS</span><h2>Late plate requests</h2></div><span className="risk-pill">{late.filter(x=>x.status==="requested").length} open</span></div>{late.length?late.slice(0,30).map(x=><div className="v2-admin-row service-exception"key={x.id}><div><b>{x.status==="requested"?"Requested":x.status==="preparing"?"Preparing":x.status==="ready"?"Ready":"Picked up"}</b><small>{memberName(x.member_id)} · {mealName(x.meal_id)} · {dateLabel(meals.find(m=>m.id===x.meal_id)?.meal_date||null)}</small></div><span>{x.notes||"No note"}</span></div>):<p>No service exceptions.</p>}</section></>}
