import React,{useEffect,useState}from"react";
import{Bell,BookOpen,ChefHat,Check,ClipboardList,Edit3,Megaphone,Printer,RefreshCw,ShieldAlert,Users,UtensilsCrossed,X}from"lucide-react";
import{supabase}from"./lib/supabase";

type Props={user:any;profile:any;onSignOut:()=>void};
type Member={id:string;full_name:string|null;role:string|null;chapter_id:string|null};
type Notice={id:string;title:string;message:string;type:string;created_at:string;read?:boolean};
type Meal={id:string;name:string;meal_date:string|null;meal_type:string;allergens:string[]};

const day=(d:string|null)=>d?new Date(d+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"}):"—";

export default function V2AdminWorkspace({user,profile,onSignOut}:Props){
 const[tab,setTab]=useState("overview"),[members,setMembers]=useState<Member[]>([]),[notices,setNotices]=useState<Notice[]>([]),[meals,setMeals]=useState<Meal[]>([]),[late,setLate]=useState<any[]>([]),[allergy,setAllergy]=useState<any[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[draftTitle,setDraftTitle]=useState(""),[draftMessage,setDraftMessage]=useState(""),[draftType,setDraftType]=useState("announcement"),[publishing,setPublishing]=useState(false);
 const name=profile?.full_name||"Administrator";
 async function load(){setLoading(true);const[m,n,me,l,a]=await Promise.all([supabase.from("profiles").select("id,full_name,role,chapter_id").order("full_name"),supabase.from("notifications").select("id,title,message,type,created_at,read").is("user_id",null).order("created_at",{ascending:false}).limit(100),supabase.from("meals").select("id,name,meal_date,meal_type,allergens").gte("meal_date",new Date().toISOString().slice(0,10)).order("meal_date").limit(100),supabase.from("late_plate_requests").select("id,meal_id,member_id,status,requested_at,notes").order("requested_at",{ascending:false}).limit(100),supabase.from("allergy_profiles").select("member_id,allergies,dietary_restrictions,notes")]);setMembers((m.data||[])as Member[]);setNotices((n.data||[])as Notice[]);setMeals((me.data||[])as Meal[]);setLate(l.data||[]);setAllergy(a.data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 const membersOnly=members.filter(x=>x.role==="member");const chefs=members.filter(x=>x.role==="chef");const admins=members.filter(x=>["admin","super_admin"].includes(String(x.role)));const openLate=late.filter(x=>x.status==="requested").length;const allergyCount=allergy.filter(x=>(x.allergies||[]).length||(x.dietary_restrictions||[]).length).length;
 async function changeRole(id:string,role:string){const{error}=await supabase.from("profiles").update({role}).eq("id",id);setMessage(error?.message||"Role updated.");if(!error)void load()}
 async function publish(){if(!draftTitle.trim()||!draftMessage.trim())return;setPublishing(true);const payload={title:draftTitle.trim(),message:draftMessage.trim(),type:draftType};let result=await supabase.from("announcements").insert(payload);if(result.error){result=await supabase.from("notifications").insert({...payload,user_id:null,read:false})}setMessage(result.error?.message||"Announcement published.");if(!result.error){setDraftTitle("");setDraftMessage("");void load()}setPublishing(false)}
 return <div className="v2-admin"><header className="v2-admin-top"><div className="v2-admin-brand"><div className="v2-mark"><UtensilsCrossed size={20}/></div><div><b>HouseEats</b><span>Tasteful Traditions · Admin</span></div></div><div className="v2-admin-actions"><button onClick={()=>void load()} aria-label="Refresh"><RefreshCw size={18}/></button><button onClick={onSignOut}>Sign out</button></div></header><main className="v2-admin-main"><div className="v2-admin-welcome"><span>ADMIN CONSOLE</span><h1>{name}</h1><p>Chapter operations, members, kitchen activity and announcements.</p></div><nav className="v2-admin-tabs">{[["overview","Overview",ClipboardList],["members","Members",Users],["kitchen","Kitchen",ChefHat],["announcements","Announcements",Megaphone],["feedback","Feedback",BookOpen]] .map(([id,label,Icon]:any)=><button key={id}className={tab===id?"active":""}onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</nav>{message&&<div className="v2-admin-message">{message}<button onClick={()=>setMessage("")}><X size={14}/></button></div>}{loading?<section className="v2-admin-card">Loading chapter data…</section>:<>{tab==="overview"&&<Overview members={membersOnly.length}chefs={chefs.length}admins={admins.length}meals={meals.length}late={openLate}allergy={allergyCount}notices={notices.length}onTab={setTab}/>} {tab==="members"&&<Members members={members}onRole={changeRole}/>} {tab==="kitchen"&&<Kitchen meals={meals}late={late}allergy={allergy}/>} {tab==="announcements"&&<Announcements notices={notices}title={draftTitle}setTitle={setDraftTitle}body={draftMessage}setBody={setDraftMessage}type={draftType}setType={setDraftType}onPublish={publish}publishing={publishing}/>} {tab==="feedback"&&<Feedback meals={meals}/>}</>}</main></div>
}
function Overview(p:any){const cards=[["Members",p.members,Users,"members"],["Chefs",p.chefs,ChefHat,"members"],["Upcoming meals",p.meals,UtensilsCrossed,"kitchen"],["Open late plates",p.late,ShieldAlert,"kitchen"],["Allergy profiles",p.allergy,ShieldAlert,"kitchen"],["Announcements",p.notices,Megaphone,"announcements"]];return <><div className="v2-admin-grid">{cards.map(([label,value,Icon,tab]:any)=><button key={label}className="v2-admin-stat"onClick={()=>p.onTab(tab)}><Icon size={20}/><span>{label}</span><b>{value}</b></button>)}</div><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>CONTROL CENTER</span><h2>V1 parity restored</h2></div><Check size={20}/></div><p>Member management, kitchen operations, allergy visibility, late plates, announcements, notifications and feedback now have dedicated V2 entry points.</p></section></>}
function Members({members,onRole}:any){return <section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>PEOPLE</span><h2>Member management</h2></div><Users size={20}/></div><div className="v2-admin-list">{members.map((m:Member)=><div className="v2-admin-row"key={m.id}><div className="person-avatar">{(m.full_name||"?").slice(0,1).toUpperCase()}</div><div className="person-copy"><b>{m.full_name||"Unnamed member"}</b><small>{m.role||"member"}{m.chapter_id?` · Chapter ${String(m.chapter_id).slice(0,8)}`:""}</small></div><select value={m.role||"member"}onChange={e=>onRole(m.id,e.target.value)}><option value="member">Member</option><option value="chef">Chef</option><option value="admin">Admin</option></select></div>)}</div></section>}
function Kitchen({meals,late,allergy}:any){const today=new Date().toISOString().slice(0,10);const todayMeals=meals.filter((m:Meal)=>m.meal_date===today);return <><section className="v2-admin-grid"><div className="v2-admin-stat"><UtensilsCrossed/><span>Today's meals</span><b>{todayMeals.length}</b></div><div className="v2-admin-stat"><ShieldAlert/><span>Open late plates</span><b>{late.filter((x:any)=>x.status==="requested").length}</b></div><div className="v2-admin-stat"><ShieldAlert/><span>Allergy profiles</span><b>{allergy.length}</b></div></section><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>UPCOMING MENU</span><h2>Kitchen schedule</h2></div><button onClick={()=>window.print()}><Printer size={17}/></button></div>{meals.length?meals.slice(0,40).map((m:Meal)=><div className="v2-admin-row"key={m.id}><div><b>{m.name}</b><small>{day(m.meal_date)} · {m.meal_type}</small></div>{m.allergens?.length?<span className="risk-pill">{m.allergens.length} allergens</span>:<span>Clear</span>}</div>):<p>No upcoming meals.</p>}</section><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>LATE PLATES</span><h2>Service exceptions</h2></div></div>{late.length?late.slice(0,30).map((x:any)=><div className="v2-admin-row"key={x.id}><div><b>{x.status||"requested"}</b><small>Member {String(x.member_id).slice(0,8)} · Meal {String(x.meal_id).slice(0,8)}</small></div><span>{x.notes||"No note"}</span></div>):<p>No late plate requests.</p>}</section></>}
function Announcements(p:any){return <><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>PUBLISH</span><h2>New announcement</h2></div><Megaphone/></div><label>Title<input value={p.title}onChange={e=>p.setTitle(e.target.value)}placeholder="Kitchen or chapter update"/></label><label>Message<textarea value={p.body}onChange={e=>p.setBody(e.target.value)}placeholder="Write the announcement…"/></label><label>Type<select value={p.type}onChange={e=>p.setType(e.target.value)}><option value="announcement">Announcement</option><option value="urgent">Urgent</option><option value="menu">Menu</option><option value="kitchen">Kitchen</option></select></label><button className="v2-admin-primary"disabled={p.publishing}onClick={p.onPublish}><Megaphone size={17}/>{p.publishing?"Publishing…":"Publish to members"}</button></section><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>HISTORY</span><h2>Recent announcements</h2></div></div>{p.notices.length?p.notices.map((n:Notice)=><article className="v2-admin-notice"key={n.id}><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString()}</small></article>):<p>No announcements yet.</p>}</section></>}
function Feedback({meals}:any){const[reviews,setReviews]=useState<any[]>([]);useEffect(()=>{void supabase.from("meal_reviews").select("id,meal_id,rating,comment,created_at").order("created_at",{ascending:false}).limit(200).then(({data})=>setReviews(data||[]))},[]);const avg=reviews.length?reviews.reduce((s:number,r:any)=>s+r.rating,0)/reviews.length:0;return <><section className="v2-admin-grid"><div className="v2-admin-stat"><BookOpen/><span>Total ratings</span><b>{reviews.length}</b></div><div className="v2-admin-stat"><BookOpen/><span>Average</span><b>{avg?avg.toFixed(1):"—"}</b></div></section><section className="v2-admin-card"><div className="v2-admin-card-head"><div><span>MEMBER VOICE</span><h2>Meal feedback</h2></div></div>{reviews.length?reviews.map((r:any)=><article className="v2-admin-notice"key={r.id}><b>{meals.find((m:Meal)=>m.id===r.meal_id)?.name||"Meal"} · {r.rating}/5</b>{r.comment&&<p>{r.comment}</p>}<small>{new Date(r.created_at).toLocaleString()}</small></article>):<p>No meal feedback yet.</p>}</section></>}
