import React,{useEffect,useState}from"react";
import{BarChart3,Check,Users,X}from"lucide-react";
import V2Workspace from"./V2Workspace";
import MealFeedbackPanel from"./components/MealFeedbackPanel";
import{supabase}from"./lib/supabase";

type Props={user:any;profile:any;onSignOut?:()=>void};
export default function V2RoleWorkspace({user,profile}:Props){const role=String(profile?.role||"member").toLowerCase();return <><V2Workspace user={user} profile={profile}/>{role==="member"&&<MealFeedbackPanel user={user} role="member"/>}{role==="chef"&&<ChefHeadcount user={user}/>}</>}
function ChefHeadcount({user}:any){const[open,setOpen]=useState(false),[rows,setRows]=useState<any[]>([]),[total,setTotal]=useState(0),[attending,setAttending]=useState(0),[loading,setLoading]=useState(false);async function load(){setLoading(true);const today=new Date().toISOString().slice(0,10);const{data:meals}=await supabase.from("meals").select("id,name,meal_type,meal_date").eq("meal_date",today).order("meal_type");const ids=(meals||[]).map((m:any)=>m.id);if(!ids.length){setRows([]);setTotal(0);setAttending(0);setLoading(false);return}const{data:rsvps}=await supabase.from("rsvps").select("meal_id,attending").in("meal_id",ids);const result=(meals||[]).map((m:any)=>{const rs=(rsvps||[]).filter((r:any)=>r.meal_id===m.id);return{...m,yes:rs.filter((r:any)=>r.attending).length,no:rs.filter((r:any)=>r.attending===false).length}});setRows(result);setTotal((rsvps||[]).length);setAttending((rsvps||[]).filter((r:any)=>r.attending).length);setLoading(false)}useEffect(()=>{if(open)void load()},[open]);return <><button className="chef-headcount-fab"onClick={()=>setOpen(true)}><BarChart3 size={17}/><span>Headcount</span></button>{open&&<div className="chef-headcount-backdrop"onClick={()=>setOpen(false)}><section className="chef-headcount-panel"onClick={e=>e.stopPropagation()}><header><div><span>TODAY'S SERVICE</span><h2>Headcount</h2></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="headcount-total"><div><Users/><b>{attending}</b><span>eating today</span></div><div><b>{total}</b><span>RSVP records</span></div></div>{loading?<p>Loading headcount…</p>:rows.length?rows.map(r=><article key={r.id}><div><b>{r.name}</b><small>{r.meal_type}</small></div><strong><Check size={14}/> {r.yes}</strong></article>):<p>No meals posted for today.</p>}<button className="headcount-refresh"onClick={()=>void load()}>Refresh headcount</button></section></div>}</>}
